//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BaoCaoVanBanDen {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BaoCaoVanBanDen() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.BaoCaoVanBanDen", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide advance search.
        /// </summary>
        internal static string lblAnTimKiemNangCao {
            get {
                return ResourceManager.GetString("lblAnTimKiemNangCao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistical reports.
        /// </summary>
        internal static string lblBaoCaoThongKe {
            get {
                return ResourceManager.GetString("lblBaoCaoThongKe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming document statistics synthesis report.
        /// </summary>
        internal static string lblBaoCaoThongKeVanBanDenTongHop {
            get {
                return ResourceManager.GetString("lblBaoCaoThongKeVanBanDenTongHop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferring out document statistics reports.
        /// </summary>
        internal static string lblBaoCaoThongKeVBDi {
            get {
                return ResourceManager.GetString("lblBaoCaoThongKeVBDi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report status process of documents.
        /// </summary>
        internal static string lblBaoCaoTinhHinhGiaiQuyetVB {
            get {
                return ResourceManager.GetString("lblBaoCaoTinhHinhGiaiQuyetVB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Incoming documents completed .
        /// </summary>
        internal static string lblBaoCaoVBDenDaXuLy {
            get {
                return ResourceManager.GetString("lblBaoCaoVBDenDaXuLy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Incoming documents company.
        /// </summary>
        internal static string lblBaoCaoVBDenDonVi {
            get {
                return ResourceManager.GetString("lblBaoCaoVBDenDonVi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string lblChon {
            get {
                return ResourceManager.GetString("lblChon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zzzz.
        /// </summary>
        internal static string lblChonDoMat {
            get {
                return ResourceManager.GetString("lblChonDoMat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Dept/Branch.
        /// </summary>
        internal static string lblChonDonVi {
            get {
                return ResourceManager.GetString("lblChonDonVi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select value.
        /// </summary>
        internal static string lblChonGiaTri {
            get {
                return ResourceManager.GetString("lblChonGiaTri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select documents category.
        /// </summary>
        internal static string lblChonLoaiVanBan {
            get {
                return ResourceManager.GetString("lblChonLoaiVanBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select user.
        /// </summary>
        internal static string lblChonNguoiDung {
            get {
                return ResourceManager.GetString("lblChonNguoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select search scope.
        /// </summary>
        internal static string lblChonPhamViTimKiem {
            get {
                return ResourceManager.GetString("lblChonPhamViTimKiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select register of documents.
        /// </summary>
        internal static string lblChonSoVanBan {
            get {
                return ResourceManager.GetString("lblChonSoVanBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unprocess.
        /// </summary>
        internal static string lblChuaButPhe {
            get {
                return ResourceManager.GetString("lblChuaButPhe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        internal static string lblChuaXuLy {
            get {
                return ResourceManager.GetString("lblChuaXuLy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending overdue.
        /// </summary>
        internal static string lblChuaXuLyQuaHan {
            get {
                return ResourceManager.GetString("lblChuaXuLyQuaHan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In term.
        /// </summary>
        internal static string lblConHan {
            get {
                return ResourceManager.GetString("lblConHan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In term process.
        /// </summary>
        internal static string lblConHanXuLy {
            get {
                return ResourceManager.GetString("lblConHanXuLy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dept/branch sent to.
        /// </summary>
        internal static string lblCoQuanDonViGuiDen {
            get {
                return ResourceManager.GetString("lblCoQuanDonViGuiDen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        internal static string lblDaButPhe {
            get {
                return ResourceManager.GetString("lblDaButPhe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executed.
        /// </summary>
        internal static string lblDaGiaiQuyet {
            get {
                return ResourceManager.GetString("lblDaGiaiQuyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        internal static string lblDangXuLy {
            get {
                return ResourceManager.GetString("lblDangXuLy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string lblDaXuLy {
            get {
                return ResourceManager.GetString("lblDaXuLy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed overdue.
        /// </summary>
        internal static string lblDaXuLyQuaHan {
            get {
                return ResourceManager.GetString("lblDaXuLyQuaHan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to due date.
        /// </summary>
        internal static string lblDenHan {
            get {
                return ResourceManager.GetString("lblDenHan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to date.
        /// </summary>
        internal static string lblDenNgay {
            get {
                return ResourceManager.GetString("lblDenNgay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to number.
        /// </summary>
        internal static string lblDenSo {
            get {
                return ResourceManager.GetString("lblDenSo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to month.
        /// </summary>
        internal static string lblDenThang {
            get {
                return ResourceManager.GetString("lblDenThang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zzzz.
        /// </summary>
        internal static string lblDoMat {
            get {
                return ResourceManager.GetString("lblDoMat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string lblDong {
            get {
                return ResourceManager.GetString("lblDong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dept/Branch.
        /// </summary>
        internal static string lblDonVi {
            get {
                return ResourceManager.GetString("lblDonVi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dept/Branch process.
        /// </summary>
        internal static string lblDonViXuLy {
            get {
                return ResourceManager.GetString("lblDonViXuLy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        internal static string lblGhiChu {
            get {
                return ResourceManager.GetString("lblGhiChu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline.
        /// </summary>
        internal static string lblHanXuLy {
            get {
                return ResourceManager.GetString("lblHanXuLy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string lblIn {
            get {
                return ResourceManager.GetString("lblIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print statistics.
        /// </summary>
        internal static string lblInThongKe {
            get {
                return ResourceManager.GetString("lblInThongKe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zzzz.
        /// </summary>
        internal static string lblKhan {
            get {
                return ResourceManager.GetString("lblKhan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process overdue.
        /// </summary>
        internal static string lblKhongCoHanXuLy {
            get {
                return ResourceManager.GetString("lblKhongCoHanXuLy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager process.
        /// </summary>
        internal static string lblLanhDaoXuLy {
            get {
                return ResourceManager.GetString("lblLanhDaoXuLy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents catergory.
        /// </summary>
        internal static string lblLoaiVanBan {
            get {
                return ResourceManager.GetString("lblLoaiVanBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zzzz.
        /// </summary>
        internal static string lblMat {
            get {
                return ResourceManager.GetString("lblMat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zzzz.
        /// </summary>
        internal static string lblMatKhan {
            get {
                return ResourceManager.GetString("lblMatKhan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string lblNam {
            get {
                return ResourceManager.GetString("lblNam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string lblNgay {
            get {
                return ResourceManager.GetString("lblNgay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string lblNgayDen {
            get {
                return ResourceManager.GetString("lblNgayDen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha noi, Date……..month…….year 20.
        /// </summary>
        internal static string lblNgayThangNam {
            get {
                return ResourceManager.GetString("lblNgayThangNam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of documents.
        /// </summary>
        internal static string lblNgayVanBan {
            get {
                return ResourceManager.GetString("lblNgayVanBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver.
        /// </summary>
        internal static string lblNguoiKyNhan {
            get {
                return ResourceManager.GetString("lblNguoiKyNhan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creater.
        /// </summary>
        internal static string lblNguoiLap {
            get {
                return ResourceManager.GetString("lblNguoiLap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter keyword.
        /// </summary>
        internal static string lblNhapTuKhoaTimKiem {
            get {
                return ResourceManager.GetString("lblNhapTuKhoaTimKiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search scope.
        /// </summary>
        internal static string lblPhamViTimKiem {
            get {
                return ResourceManager.GetString("lblPhamViTimKiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overdue.
        /// </summary>
        internal static string lblQuaHan {
            get {
                return ResourceManager.GetString("lblQuaHan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overdue process.
        /// </summary>
        internal static string lblQuaHanXuLy {
            get {
                return ResourceManager.GetString("lblQuaHanXuLy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill number.
        /// </summary>
        internal static string lblSoBill {
            get {
                return ResourceManager.GetString("lblSoBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal number.
        /// </summary>
        internal static string lblSoBuuDien {
            get {
                return ResourceManager.GetString("lblSoBuuDien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        internal static string lblSoDen {
            get {
                return ResourceManager.GetString("lblSoDen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol number.
        /// </summary>
        internal static string lblSoKiHieu {
            get {
                return ResourceManager.GetString("lblSoKiHieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Register books.
        /// </summary>
        internal static string lblSoVanBan {
            get {
                return ResourceManager.GetString("lblSoVanBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        internal static string lblSTT {
            get {
                return ResourceManager.GetString("lblSTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string lblTatCa {
            get {
                return ResourceManager.GetString("lblTatCa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string lblThang {
            get {
                return ResourceManager.GetString("lblThang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics handled status of Incoming documents .
        /// </summary>
        internal static string lblThongKeTinhHinhXuLyVBDen {
            get {
                return ResourceManager.GetString("lblThongKeTinhHinhXuLyVBDen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics Incoming documents .
        /// </summary>
        internal static string lblThongKeVanBanDen {
            get {
                return ResourceManager.GetString("lblThongKeVanBanDen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string lblThuong {
            get {
                return ResourceManager.GetString("lblThuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing rogress .
        /// </summary>
        internal static string lblTienDoXuLyVBCua {
            get {
                return ResourceManager.GetString("lblTienDoXuLyVBCua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string lblTimKiem {
            get {
                return ResourceManager.GetString("lblTimKiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search advanced.
        /// </summary>
        internal static string lblTimKiemNangCao {
            get {
                return ResourceManager.GetString("lblTimKiemNangCao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In search.
        /// </summary>
        internal static string lblTimKiemTrong {
            get {
                return ResourceManager.GetString("lblTimKiemTrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing situation.
        /// </summary>
        internal static string lblTinhHinhGiaiQuyetVB {
            get {
                return ResourceManager.GetString("lblTinhHinhGiaiQuyetVB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string lblTinhTrang {
            get {
                return ResourceManager.GetString("lblTinhTrang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string lblTong {
            get {
                return ResourceManager.GetString("lblTong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string lblTrangChu {
            get {
                return ResourceManager.GetString("lblTrangChu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string lblTrangThai {
            get {
                return ResourceManager.GetString("lblTrangThai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abstract.
        /// </summary>
        internal static string lblTrichYeu {
            get {
                return ResourceManager.GetString("lblTrichYeu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto update to time now.
        /// </summary>
        internal static string lblTuDongCapNhatToiThoiGianHienTai {
            get {
                return ResourceManager.GetString("lblTuDongCapNhatToiThoiGianHienTai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword.
        /// </summary>
        internal static string lblTuKhoa {
            get {
                return ResourceManager.GetString("lblTuKhoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From date.
        /// </summary>
        internal static string lblTuNgay {
            get {
                return ResourceManager.GetString("lblTuNgay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From No..
        /// </summary>
        internal static string lblTuSo {
            get {
                return ResourceManager.GetString("lblTuSo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        internal static string lblVanBan {
            get {
                return ResourceManager.GetString("lblVanBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming documents dept / branch.
        /// </summary>
        internal static string lblVanBanDenDonVi {
            get {
                return ResourceManager.GetString("lblVanBanDenDonVi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferring out documents.
        /// </summary>
        internal static string lblVanBanDi {
            get {
                return ResourceManager.GetString("lblVanBanDi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents indue.
        /// </summary>
        internal static string lblVanBanDungHan {
            get {
                return ResourceManager.GetString("lblVanBanDungHan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vietnam.
        /// </summary>
        internal static string lblVietNam {
            get {
                return ResourceManager.GetString("lblVietNam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string lblXemVanBan {
            get {
                return ResourceManager.GetString("lblXemVanBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export .xls.
        /// </summary>
        internal static string lblXuatExcel {
            get {
                return ResourceManager.GetString("lblXuatExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export .pdf.
        /// </summary>
        internal static string lblXuatPDF {
            get {
                return ResourceManager.GetString("lblXuatPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export .doc.
        /// </summary>
        internal static string lblXuatWord {
            get {
                return ResourceManager.GetString("lblXuatWord", resourceCulture);
            }
        }
    }
}
