//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BaoCaoVanBanDi {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BaoCaoVanBanDi() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.BaoCaoVanBanDi", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery documents statistics reports.
        /// </summary>
        internal static string lblBaoCaoThongKeVanBanDi {
            get {
                return ResourceManager.GetString("lblBaoCaoThongKeVanBanDi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery documents statistics reports.
        /// </summary>
        internal static string lblBaoCaoThongKeVBDi {
            get {
                return ResourceManager.GetString("lblBaoCaoThongKeVBDi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery documents Statistics synthesis reports.
        /// </summary>
        internal static string lblBaoCaoThongKeVBDiTongHop {
            get {
                return ResourceManager.GetString("lblBaoCaoThongKeVBDiTongHop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin.
        /// </summary>
        internal static string lblBatDauTu {
            get {
                return ResourceManager.GetString("lblBatDauTu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Drafting dept / branch.
        /// </summary>
        internal static string lblChonDonViSoanThao {
            get {
                return ResourceManager.GetString("lblChonDonViSoanThao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Documents category.
        /// </summary>
        internal static string lblChonLoaiVanBan {
            get {
                return ResourceManager.GetString("lblChonLoaiVanBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Signer.
        /// </summary>
        internal static string lblChonNguoiKy {
            get {
                return ResourceManager.GetString("lblChonNguoiKy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Register books.
        /// </summary>
        internal static string lblChonSoVanBan {
            get {
                return ResourceManager.GetString("lblChonSoVanBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string lblDong {
            get {
                return ResourceManager.GetString("lblDong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drafting dept/branch.
        /// </summary>
        internal static string lblDonViSoanThao {
            get {
                return ResourceManager.GetString("lblDonViSoanThao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print .
        /// </summary>
        internal static string lblInThongKe {
            get {
                return ResourceManager.GetString("lblInThongKe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string lblInThongKeVanBanDi {
            get {
                return ResourceManager.GetString("lblInThongKeVanBanDi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string lblKetThuc {
            get {
                return ResourceManager.GetString("lblKetThuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents category.
        /// </summary>
        internal static string lblLoaiVanBan {
            get {
                return ResourceManager.GetString("lblLoaiVanBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string lblNam {
            get {
                return ResourceManager.GetString("lblNam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string lblNgay {
            get {
                return ResourceManager.GetString("lblNgay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of validity.
        /// </summary>
        internal static string lblNgayBanHanh {
            get {
                return ResourceManager.GetString("lblNgayBanHanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string lblNgayVanBan {
            get {
                return ResourceManager.GetString("lblNgayVanBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signer.
        /// </summary>
        internal static string lblNguoiKy {
            get {
                return ResourceManager.GetString("lblNguoiKy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string lblNoiNhan {
            get {
                return ResourceManager.GetString("lblNoiNhan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope.
        /// </summary>
        internal static string lblPhamVi {
            get {
                return ResourceManager.GetString("lblPhamVi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register of Transferring out documents.
        /// </summary>
        internal static string lblSoDKVanBanDi {
            get {
                return ResourceManager.GetString("lblSoDKVanBanDi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S/N.
        /// </summary>
        internal static string lblSoKiHieu {
            get {
                return ResourceManager.GetString("lblSoKiHieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        internal static string lblSoLuong {
            get {
                return ResourceManager.GetString("lblSoLuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register books.
        /// </summary>
        internal static string lblSoVanBan {
            get {
                return ResourceManager.GetString("lblSoVanBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        internal static string lblSTT {
            get {
                return ResourceManager.GetString("lblSTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string lblThang {
            get {
                return ResourceManager.GetString("lblThang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery documents statistics synthesis.
        /// </summary>
        internal static string lblThongKeTongHopVBDi {
            get {
                return ResourceManager.GetString("lblThongKeTongHopVBDi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string lblTimKiem {
            get {
                return ResourceManager.GetString("lblTimKiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string lblTongSoVanBanLa {
            get {
                return ResourceManager.GetString("lblTongSoVanBanLa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string lblTrangChu {
            get {
                return ResourceManager.GetString("lblTrangChu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abstract.
        /// </summary>
        internal static string lblTrichYeu {
            get {
                return ResourceManager.GetString("lblTrichYeu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords.
        /// </summary>
        internal static string lblTuKhoa {
            get {
                return ResourceManager.GetString("lblTuKhoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Keywords.
        /// </summary>
        internal static string lblTuKhoaTimKiem {
            get {
                return ResourceManager.GetString("lblTuKhoaTimKiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        internal static string lblVanBan {
            get {
                return ResourceManager.GetString("lblVanBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery documents.
        /// </summary>
        internal static string lblVanBanDi {
            get {
                return ResourceManager.GetString("lblVanBanDi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zzzz.
        /// </summary>
        internal static string lblVanBanDiMat {
            get {
                return ResourceManager.GetString("lblVanBanDiMat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Transferring out documents.
        /// </summary>
        internal static string lblVanBanDiThuong {
            get {
                return ResourceManager.GetString("lblVanBanDiThuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vietnam.
        /// </summary>
        internal static string lblVietNam {
            get {
                return ResourceManager.GetString("lblVietNam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export .xls.
        /// </summary>
        internal static string lblXuatExcel {
            get {
                return ResourceManager.GetString("lblXuatExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export .doc.
        /// </summary>
        internal static string lblXuatWord {
            get {
                return ResourceManager.GetString("lblXuatWord", resourceCulture);
            }
        }
    }
}
