//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BieuMau {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BieuMau() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.BieuMau", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string btnDong {
            get {
                return ResourceManager.GetString("btnDong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string btnLuu {
            get {
                return ResourceManager.GetString("btnLuu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retype.
        /// </summary>
        internal static string btnNhapLai {
            get {
                return ResourceManager.GetString("btnNhapLai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string btnThoat {
            get {
                return ResourceManager.GetString("btnThoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide selected list.
        /// </summary>
        internal static string lblAnDanhSachDaChon {
            get {
                return ResourceManager.GetString("lblAnDanhSachDaChon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden template - forms successfully.
        /// </summary>
        internal static string lblAnThanhCongBieuMau {
            get {
                return ResourceManager.GetString("lblAnThanhCongBieuMau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to required information.
        /// </summary>
        internal static string lblBatBuocNhapThongTin {
            get {
                return ResourceManager.GetString("lblBatBuocNhapThongTin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to template.
        /// </summary>
        internal static string lblBieuMau {
            get {
                return ResourceManager.GetString("lblBieuMau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template - form is currently hidden.
        /// </summary>
        internal static string lblBieuMauHienDangAn {
            get {
                return ResourceManager.GetString("lblBieuMauHienDangAn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The template - form is currently displayed.
        /// </summary>
        internal static string lblBieuMauHienDangHienThi {
            get {
                return ResourceManager.GetString("lblBieuMauHienDangHienThi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        internal static string lblBieuMauinHoa {
            get {
                return ResourceManager.GetString("lblBieuMauinHoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forms can not be deleted because they are in use.
        /// </summary>
        internal static string lblBieuMauKhongXoaDuocDoDangSuDung {
            get {
                return ResourceManager.GetString("lblBieuMauKhongXoaDuocDoDangSuDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields marked.
        /// </summary>
        internal static string lblCacTruongCoDau {
            get {
                return ResourceManager.GetString("lblCacTruongCoDau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update template - forms.
        /// </summary>
        internal static string lblCapNhatBieuMau {
            get {
                return ResourceManager.GetString("lblCapNhatBieuMau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template detail.
        /// </summary>
        internal static string lblChiTietBieuMau {
            get {
                return ResourceManager.GetString("lblChiTietBieuMau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select file attachment.
        /// </summary>
        internal static string lblChonFileDinhKem {
            get {
                return ResourceManager.GetString("lblChonFileDinhKem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select search scope.
        /// </summary>
        internal static string lblChonPhamViTimKiem {
            get {
                return ResourceManager.GetString("lblChonPhamViTimKiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error !.
        /// </summary>
        internal static string lblCoLoiXayRa {
            get {
                return ResourceManager.GetString("lblCoLoiXayRa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error !.
        /// </summary>
        internal static string lblDaCoLoiXayRa {
            get {
                return ResourceManager.GetString("lblDaCoLoiXayRa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to already exists.
        /// </summary>
        internal static string lblDaTonTai {
            get {
                return ResourceManager.GetString("lblDaTonTai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted successfully.
        /// </summary>
        internal static string lblDaXoaThanhCong {
            get {
                return ResourceManager.GetString("lblDaXoaThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File attachment.
        /// </summary>
        internal static string lblFileDinhKem {
            get {
                return ResourceManager.GetString("lblFileDinhKem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show selected list.
        /// </summary>
        internal static string lblHienThiDanhSachDaChon {
            get {
                return ResourceManager.GetString("lblHienThiDanhSachDaChon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show template - forms successfully.
        /// </summary>
        internal static string lblHienThiThanhCongBieuMau {
            get {
                return ResourceManager.GetString("lblHienThiThanhCongBieuMau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zzzz.
        /// </summary>
        internal static string lblKiSoVB {
            get {
                return ResourceManager.GetString("lblKiSoVB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        internal static string lblLuuY {
            get {
                return ResourceManager.GetString("lblLuuY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string lblMoTa {
            get {
                return ResourceManager.GetString("lblMoTa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type a description.
        /// </summary>
        internal static string lblNhapMoTa {
            get {
                return ResourceManager.GetString("lblNhapMoTa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the template name.
        /// </summary>
        internal static string lblNhapTenBieuMau {
            get {
                return ResourceManager.GetString("lblNhapTenBieuMau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type No..
        /// </summary>
        internal static string lblNhapThuTu {
            get {
                return ResourceManager.GetString("lblNhapThuTu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type search keywords.
        /// </summary>
        internal static string lblNhapTuKhoaTimKiem {
            get {
                return ResourceManager.GetString("lblNhapTuKhoaTimKiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope.
        /// </summary>
        internal static string lblPhamVi {
            get {
                return ResourceManager.GetString("lblPhamVi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template management.
        /// </summary>
        internal static string lblQuanLyBieuMau {
            get {
                return ResourceManager.GetString("lblQuanLyBieuMau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use.
        /// </summary>
        internal static string lblSuDung {
            get {
                return ResourceManager.GetString("lblSuDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template name.
        /// </summary>
        internal static string lblTenBieuMau {
            get {
                return ResourceManager.GetString("lblTenBieuMau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to successfully.
        /// </summary>
        internal static string lblThanhCong {
            get {
                return ResourceManager.GetString("lblThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add continuous.
        /// </summary>
        internal static string lblThemLienTiep {
            get {
                return ResourceManager.GetString("lblThemLienTiep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string lblThemMoi {
            get {
                return ResourceManager.GetString("lblThemMoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new template - forms.
        /// </summary>
        internal static string lblThemMoiBieuMau {
            get {
                return ResourceManager.GetString("lblThemMoiBieuMau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        internal static string lblThongBao {
            get {
                return ResourceManager.GetString("lblThongBao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        internal static string lblThuTu {
            get {
                return ResourceManager.GetString("lblThuTu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string lblTimKiem {
            get {
                return ResourceManager.GetString("lblTimKiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In search.
        /// </summary>
        internal static string lblTimKiemTrong {
            get {
                return ResourceManager.GetString("lblTimKiemTrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string lblTrangChu {
            get {
                return ResourceManager.GetString("lblTrangChu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword.
        /// </summary>
        internal static string lblTuKhoa {
            get {
                return ResourceManager.GetString("lblTuKhoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string lblXemTruoc {
            get {
                return ResourceManager.GetString("lblXemTruoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected list.
        /// </summary>
        internal static string lblXoaDanhSachDaChon {
            get {
                return ResourceManager.GetString("lblXoaDanhSachDaChon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete file attachment.
        /// </summary>
        internal static string lblXoaFileDinhKem {
            get {
                return ResourceManager.GetString("lblXoaFileDinhKem", resourceCulture);
            }
        }
    }
}
