//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DanhMucXe {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DanhMucXe() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DanhMucXe", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update vehicle status.
        /// </summary>
        internal static string lblCapNhatTrangThaiXe {
            get {
                return ResourceManager.GetString("lblCapNhatTrangThaiXe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed vehicle list.
        /// </summary>
        internal static string lblChiTietDanhMucXe {
            get {
                return ResourceManager.GetString("lblChiTietDanhMucXe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed booking information.
        /// </summary>
        internal static string lblChiTietThongTinDatXe {
            get {
                return ResourceManager.GetString("lblChiTietThongTinDatXe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not used yet.
        /// </summary>
        internal static string lblChuaSuDung {
            get {
                return ResourceManager.GetString("lblChuaSuDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Still empty.
        /// </summary>
        internal static string lblConTrong {
            get {
                return ResourceManager.GetString("lblConTrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved.
        /// </summary>
        internal static string lblDaDuocDat {
            get {
                return ResourceManager.GetString("lblDaDuocDat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle catalog.
        /// </summary>
        internal static string lblDanhMucXe {
            get {
                return ResourceManager.GetString("lblDanhMucXe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used.
        /// </summary>
        internal static string lblDaSuDung {
            get {
                return ResourceManager.GetString("lblDaSuDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        internal static string lblDiemDen {
            get {
                return ResourceManager.GetString("lblDiemDen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point away.
        /// </summary>
        internal static string lblDiemDi {
            get {
                return ResourceManager.GetString("lblDiemDi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change car.
        /// </summary>
        internal static string lblDoiXe {
            get {
                return ResourceManager.GetString("lblDoiXe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string lblDong {
            get {
                return ResourceManager.GetString("lblDong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string lblDonVi {
            get {
                return ResourceManager.GetString("lblDonVi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse car reservations.
        /// </summary>
        internal static string lblDuyetDatXe {
            get {
                return ResourceManager.GetString("lblDuyetDatXe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit a reservation request successfully..
        /// </summary>
        internal static string lblGuiYeuCauDatXeThanhCong {
            get {
                return ResourceManager.GetString("lblGuiYeuCauDatXeThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string lblHuy {
            get {
                return ResourceManager.GetString("lblHuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range of vehicle.
        /// </summary>
        internal static string lblLoaiXe {
            get {
                return ResourceManager.GetString("lblLoaiXe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        internal static string lblLyDo {
            get {
                return ResourceManager.GetString("lblLyDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string lblMoTa {
            get {
                return ResourceManager.GetString("lblMoTa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribers.
        /// </summary>
        internal static string lblNguoiDangKy {
            get {
                return ResourceManager.GetString("lblNguoiDangKy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator.
        /// </summary>
        internal static string lblNguoiTao {
            get {
                return ResourceManager.GetString("lblNguoiTao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participants.
        /// </summary>
        internal static string lblNguoiThamGia {
            get {
                return ResourceManager.GetString("lblNguoiThamGia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter point away.
        /// </summary>
        internal static string lblNhapDiemDen {
            get {
                return ResourceManager.GetString("lblNhapDiemDen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter destination.
        /// </summary>
        internal static string lblNhapDiemDi {
            get {
                return ResourceManager.GetString("lblNhapDiemDi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter email.
        /// </summary>
        internal static string lblNhapEmail {
            get {
                return ResourceManager.GetString("lblNhapEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retype.
        /// </summary>
        internal static string lblNhapLai {
            get {
                return ResourceManager.GetString("lblNhapLai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the reason for the decline.
        /// </summary>
        internal static string lblNhapLyDoTuChoi {
            get {
                return ResourceManager.GetString("lblNhapLyDoTuChoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a description.
        /// </summary>
        internal static string lblNhapMoTa {
            get {
                return ResourceManager.GetString("lblNhapMoTa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your phone number.
        /// </summary>
        internal static string lblNhapSoDienThoai {
            get {
                return ResourceManager.GetString("lblNhapSoDienThoai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the unit name.
        /// </summary>
        internal static string lblNhapTenDonVi {
            get {
                return ResourceManager.GetString("lblNhapTenDonVi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name of the vehicle.
        /// </summary>
        internal static string lblNhapTenLoaiXe {
            get {
                return ResourceManager.GetString("lblNhapTenLoaiXe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name of the subscriber.
        /// </summary>
        internal static string lblNhapTenNguoiDangKy {
            get {
                return ResourceManager.GetString("lblNhapTenNguoiDangKy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the join component.
        /// </summary>
        internal static string lblNhapThanhPhanThamGia {
            get {
                return ResourceManager.GetString("lblNhapThanhPhanThamGia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter search keywords.
        /// </summary>
        internal static string lblNhapTuKhoaTimKiem {
            get {
                return ResourceManager.GetString("lblNhapTuKhoaTimKiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit.
        /// </summary>
        internal static string lblPhamVi {
            get {
                return ResourceManager.GetString("lblPhamVi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string lblPhongBan {
            get {
                return ResourceManager.GetString("lblPhongBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAR LISTING MANAGEMENT.
        /// </summary>
        internal static string lblQuanLyDanhMucXe {
            get {
                return ResourceManager.GetString("lblQuanLyDanhMucXe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage car reservation information.
        /// </summary>
        internal static string lblQuanLyThongTinDatXe {
            get {
                return ResourceManager.GetString("lblQuanLyThongTinDatXe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle management.
        /// </summary>
        internal static string lblQuanLyXe {
            get {
                return ResourceManager.GetString("lblQuanLyXe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string lblSoDienThoai {
            get {
                return ResourceManager.GetString("lblSoDienThoai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of people.
        /// </summary>
        internal static string lblSoNguoi {
            get {
                return ResourceManager.GetString("lblSoNguoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use.
        /// </summary>
        internal static string lblSuDung {
            get {
                return ResourceManager.GetString("lblSuDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of vehicle.
        /// </summary>
        internal static string lblTenLoaiXe {
            get {
                return ResourceManager.GetString("lblTenLoaiXe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredient.
        /// </summary>
        internal static string lblThanhPhan {
            get {
                return ResourceManager.GetString("lblThanhPhan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add more.
        /// </summary>
        internal static string lblThemLienTiep {
            get {
                return ResourceManager.GetString("lblThemLienTiep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new.
        /// </summary>
        internal static string lblThemMoi {
            get {
                return ResourceManager.GetString("lblThemMoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string lblThoat {
            get {
                return ResourceManager.GetString("lblThoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string lblThoiGian {
            get {
                return ResourceManager.GetString("lblThoiGian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking information.
        /// </summary>
        internal static string lblThongTinDatXe {
            get {
                return ResourceManager.GetString("lblThongTinDatXe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string lblThuTu {
            get {
                return ResourceManager.GetString("lblThuTu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string lblTimKiem {
            get {
                return ResourceManager.GetString("lblTimKiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string lblTrangChu {
            get {
                return ResourceManager.GetString("lblTrangChu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string lblTrangThai {
            get {
                return ResourceManager.GetString("lblTrangThai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car status.
        /// </summary>
        internal static string lblTrangThaiXe {
            get {
                return ResourceManager.GetString("lblTrangThaiXe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refusal to approve the booking request.
        /// </summary>
        internal static string lblTuChoiDuyetYeuCauDatXe {
            get {
                return ResourceManager.GetString("lblTuChoiDuyetYeuCauDatXe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords.
        /// </summary>
        internal static string lblTuKhoa {
            get {
                return ResourceManager.GetString("lblTuKhoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Vehicles.
        /// </summary>
        internal static string lblXe {
            get {
                return ResourceManager.GetString("lblXe", resourceCulture);
            }
        }
    }
}
