//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DanhMucPhongHop {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DanhMucPhongHop() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DanhMucPhongHop", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string bcrTrangChu {
            get {
                return ResourceManager.GetString("bcrTrangChu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide selected list.
        /// </summary>
        internal static string lblAnDSDaChon {
            get {
                return ResourceManager.GetString("lblAnDSDaChon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete?.
        /// </summary>
        internal static string lblBanCoChacXoaSuKien {
            get {
                return ResourceManager.GetString("lblBanCoChacXoaSuKien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type required information.
        /// </summary>
        internal static string lblBatBuocNhapThongTin {
            get {
                return ResourceManager.GetString("lblBatBuocNhapThongTin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields marked.
        /// </summary>
        internal static string lblCacTruongCoDau {
            get {
                return ResourceManager.GetString("lblCacTruongCoDau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail meeting room .
        /// </summary>
        internal static string lblChiTietPhongHop {
            get {
                return ResourceManager.GetString("lblChiTietPhongHop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select searching scope.
        /// </summary>
        internal static string lblChonPhamViTimKiem {
            get {
                return ResourceManager.GetString("lblChonPhamViTimKiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error !.
        /// </summary>
        internal static string lblCoLoiXayRa {
            get {
                return ResourceManager.GetString("lblCoLoiXayRa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error !.
        /// </summary>
        internal static string lblDaCoLoiXayRa {
            get {
                return ResourceManager.GetString("lblDaCoLoiXayRa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalogues meeting room .
        /// </summary>
        internal static string lblDanhMucPhongHop {
            get {
                return ResourceManager.GetString("lblDanhMucPhongHop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string lblDiaDiem {
            get {
                return ResourceManager.GetString("lblDiaDiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        internal static string lblDienTich {
            get {
                return ResourceManager.GetString("lblDienTich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string lblDong {
            get {
                return ResourceManager.GetString("lblDong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhide selected list.
        /// </summary>
        internal static string lblHienThiDSDaChon {
            get {
                return ResourceManager.GetString("lblHienThiDSDaChon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        internal static string lblLuuY {
            get {
                return ResourceManager.GetString("lblLuuY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type location.
        /// </summary>
        internal static string lblNhapDiaDIem {
            get {
                return ResourceManager.GetString("lblNhapDiaDIem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Area.
        /// </summary>
        internal static string lblNhapDienTich {
            get {
                return ResourceManager.GetString("lblNhapDienTich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retype.
        /// </summary>
        internal static string lblNhapLai {
            get {
                return ResourceManager.GetString("lblNhapLai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type capacity.
        /// </summary>
        internal static string lblNhapSucChua {
            get {
                return ResourceManager.GetString("lblNhapSucChua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type name of meeting room.
        /// </summary>
        internal static string lblNhapTenPhongHop {
            get {
                return ResourceManager.GetString("lblNhapTenPhongHop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type equipment.
        /// </summary>
        internal static string lblNhapTrangThietBi {
            get {
                return ResourceManager.GetString("lblNhapTrangThietBi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type searching key word.
        /// </summary>
        internal static string lblNhapTuKhoaTimKiem {
            get {
                return ResourceManager.GetString("lblNhapTuKhoaTimKiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        internal static string lblNoiDung {
            get {
                return ResourceManager.GetString("lblNoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope.
        /// </summary>
        internal static string lblPhamVi {
            get {
                return ResourceManager.GetString("lblPhamVi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management meeting room catelogues.
        /// </summary>
        internal static string lblQuanLyDanhMucPhongHop {
            get {
                return ResourceManager.GetString("lblQuanLyDanhMucPhongHop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity.
        /// </summary>
        internal static string lblSucChua {
            get {
                return ResourceManager.GetString("lblSucChua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use.
        /// </summary>
        internal static string lblSuDung {
            get {
                return ResourceManager.GetString("lblSuDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of meeting room.
        /// </summary>
        internal static string lblTenPhongHop {
            get {
                return ResourceManager.GetString("lblTenPhongHop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add continuous.
        /// </summary>
        internal static string lblThemLienTiep {
            get {
                return ResourceManager.GetString("lblThemLienTiep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string lblThemMoi {
            get {
                return ResourceManager.GetString("lblThemMoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string lblThoat {
            get {
                return ResourceManager.GetString("lblThoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        internal static string lblThongBao {
            get {
                return ResourceManager.GetString("lblThongBao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        internal static string lblThuTu {
            get {
                return ResourceManager.GetString("lblThuTu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display No..
        /// </summary>
        internal static string lblThuTuHienThi {
            get {
                return ResourceManager.GetString("lblThuTuHienThi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string lblTimKiem {
            get {
                return ResourceManager.GetString("lblTimKiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in.
        /// </summary>
        internal static string lblTimKiemTrong {
            get {
                return ResourceManager.GetString("lblTimKiemTrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        internal static string lblTrangThietBi {
            get {
                return ResourceManager.GetString("lblTrangThietBi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword.
        /// </summary>
        internal static string lblTuKhoa {
            get {
                return ResourceManager.GetString("lblTuKhoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected list.
        /// </summary>
        internal static string lblXoaDSDaChon {
            get {
                return ResourceManager.GetString("lblXoaDSDaChon", resourceCulture);
            }
        }
    }
}
