//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DanhMuc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DanhMuc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DanhMuc", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide selected list.
        /// </summary>
        internal static string lblAnDanhSachDaChon {
            get {
                return ResourceManager.GetString("lblAnDanhSachDaChon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type required information.
        /// </summary>
        internal static string lblBatBuocNhapThongTin {
            get {
                return ResourceManager.GetString("lblBatBuocNhapThongTin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields marked.
        /// </summary>
        internal static string lblCacTruongCoDau {
            get {
                return ResourceManager.GetString("lblCacTruongCoDau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalogues detail.
        /// </summary>
        internal static string lblChiTietDanhMuc {
            get {
                return ResourceManager.GetString("lblChiTietDanhMuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value category details.
        /// </summary>
        internal static string lblChiTietDanhMucGiaTri {
            get {
                return ResourceManager.GetString("lblChiTietDanhMucGiaTri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select function to use.
        /// </summary>
        internal static string lblChonChucNangSuDung {
            get {
                return ResourceManager.GetString("lblChonChucNangSuDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select catalogues.
        /// </summary>
        internal static string lblChonDanhMuc {
            get {
                return ResourceManager.GetString("lblChonDanhMuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select search scope.
        /// </summary>
        internal static string lblChonPhamViTimKiem {
            get {
                return ResourceManager.GetString("lblChonPhamViTimKiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function.
        /// </summary>
        internal static string lblChucNang {
            get {
                return ResourceManager.GetString("lblChucNang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function to use.
        /// </summary>
        internal static string lblChucNangSuDung {
            get {
                return ResourceManager.GetString("lblChucNangSuDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes .
        /// </summary>
        internal static string lblCo {
            get {
                return ResourceManager.GetString("lblCo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error !.
        /// </summary>
        internal static string lblCoLoiXayRa {
            get {
                return ResourceManager.GetString("lblCoLoiXayRa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error !.
        /// </summary>
        internal static string lblDaCoLoiXayRa {
            get {
                return ResourceManager.GetString("lblDaCoLoiXayRa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalogues.
        /// </summary>
        internal static string lblDanhMuc {
            get {
                return ResourceManager.GetString("lblDanhMuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value catalogues.
        /// </summary>
        internal static string lblDanhMucGiaTri {
            get {
                return ResourceManager.GetString("lblDanhMucGiaTri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of function to use.
        /// </summary>
        internal static string lblDanhSachChucNangSuDung {
            get {
                return ResourceManager.GetString("lblDanhSachChucNangSuDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string lblDong {
            get {
                return ResourceManager.GetString("lblDong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string lblDongLai {
            get {
                return ResourceManager.GetString("lblDongLai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value data.
        /// </summary>
        internal static string lblDuLieuGiaTri {
            get {
                return ResourceManager.GetString("lblDuLieuGiaTri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string lblHeThong {
            get {
                return ResourceManager.GetString("lblHeThong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhide selected list.
        /// </summary>
        internal static string lblHienThiDanhSachDaChon {
            get {
                return ResourceManager.GetString("lblHienThiDanhSachDaChon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string lblKhong {
            get {
                return ResourceManager.GetString("lblKhong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string lblLuu {
            get {
                return ResourceManager.GetString("lblLuu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string lblLuuY {
            get {
                return ResourceManager.GetString("lblLuuY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string lblMoTa {
            get {
                return ResourceManager.GetString("lblMoTa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retype.
        /// </summary>
        internal static string lblNhapLai {
            get {
                return ResourceManager.GetString("lblNhapLai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type a description.
        /// </summary>
        internal static string lblNhapMoTa {
            get {
                return ResourceManager.GetString("lblNhapMoTa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the catalogues.
        /// </summary>
        internal static string lblNhapTenDanhMuc {
            get {
                return ResourceManager.GetString("lblNhapTenDanhMuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a category name value.
        /// </summary>
        internal static string lblNhapTenDanhMucGiaTri {
            get {
                return ResourceManager.GetString("lblNhapTenDanhMucGiaTri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the English transliteration category name.
        /// </summary>
        internal static string lblNhapTenDanhMucGiaTriChuyenNguAnh {
            get {
                return ResourceManager.GetString("lblNhapTenDanhMucGiaTriChuyenNguAnh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the abbreviation name.
        /// </summary>
        internal static string lblNhapTenVietTat {
            get {
                return ResourceManager.GetString("lblNhapTenVietTat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type No..
        /// </summary>
        internal static string lblNhapThuTu {
            get {
                return ResourceManager.GetString("lblNhapThuTu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter search keyword.
        /// </summary>
        internal static string lblNhapTuKhoaTimKiem {
            get {
                return ResourceManager.GetString("lblNhapTuKhoaTimKiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalogues group.
        /// </summary>
        internal static string lblNhomDanhMuc {
            get {
                return ResourceManager.GetString("lblNhomDanhMuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope.
        /// </summary>
        internal static string lblPhamVi {
            get {
                return ResourceManager.GetString("lblPhamVi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management catalogues.
        /// </summary>
        internal static string lblQuanLyDanhMuc {
            get {
                return ResourceManager.GetString("lblQuanLyDanhMuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management catalogues of salary.
        /// </summary>
        internal static string lblQuanLyDanhMucLuong {
            get {
                return ResourceManager.GetString("lblQuanLyDanhMucLuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage catalog data.
        /// </summary>
        internal static string lblQuanLyDuLieuDanhMuc {
            get {
                return ResourceManager.GetString("lblQuanLyDuLieuDanhMuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        internal static string lblSTT {
            get {
                return ResourceManager.GetString("lblSTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use.
        /// </summary>
        internal static string lblSuDung {
            get {
                return ResourceManager.GetString("lblSuDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string lblTen {
            get {
                return ResourceManager.GetString("lblTen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalogues name.
        /// </summary>
        internal static string lblTenDanhMuc {
            get {
                return ResourceManager.GetString("lblTenDanhMuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value category name.
        /// </summary>
        internal static string lblTenDanhMucGiaTri {
            get {
                return ResourceManager.GetString("lblTenDanhMucGiaTri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English name value translation category name.
        /// </summary>
        internal static string lblTenDanhMucGiaTriChuyenNguAnh {
            get {
                return ResourceManager.GetString("lblTenDanhMucGiaTriChuyenNguAnh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbreviated name.
        /// </summary>
        internal static string lblTenVietTat {
            get {
                return ResourceManager.GetString("lblTenVietTat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add continuous.
        /// </summary>
        internal static string lblThemLienTiep {
            get {
                return ResourceManager.GetString("lblThemLienTiep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string lblThemMoi {
            get {
                return ResourceManager.GetString("lblThemMoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string lblThoat {
            get {
                return ResourceManager.GetString("lblThoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        internal static string lblThongBao {
            get {
                return ResourceManager.GetString("lblThongBao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        internal static string lblThuTu {
            get {
                return ResourceManager.GetString("lblThuTu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string lblTimKiem {
            get {
                return ResourceManager.GetString("lblTimKiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in.
        /// </summary>
        internal static string lblTimKiemTrong {
            get {
                return ResourceManager.GetString("lblTimKiemTrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string lblTrangChu {
            get {
                return ResourceManager.GetString("lblTrangChu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword.
        /// </summary>
        internal static string lblTuKhoa {
            get {
                return ResourceManager.GetString("lblTuKhoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbreviation.
        /// </summary>
        internal static string lblVietTat {
            get {
                return ResourceManager.GetString("lblVietTat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected list.
        /// </summary>
        internal static string lblXoaDanhSachDaChon {
            get {
                return ResourceManager.GetString("lblXoaDanhSachDaChon", resourceCulture);
            }
        }
    }
}
