//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DonVi {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DonVi() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DonVi", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to required input information.
        /// </summary>
        internal static string lblBatBuocNhapThongTin {
            get {
                return ResourceManager.GetString("lblBatBuocNhapThongTin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All blank boxes have.
        /// </summary>
        internal static string lblCacTruongCoDau {
            get {
                return ResourceManager.GetString("lblCacTruongCoDau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail unit.
        /// </summary>
        internal static string lblChiTietDonVi {
            get {
                return ResourceManager.GetString("lblChiTietDonVi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose unit.
        /// </summary>
        internal static string lblChonDonVi {
            get {
                return ResourceManager.GetString("lblChonDonVi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose representative.
        /// </summary>
        internal static string lblChonNguoiDaiDien {
            get {
                return ResourceManager.GetString("lblChonNguoiDaiDien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred.
        /// </summary>
        internal static string lblCoLoiXayRa {
            get {
                return ResourceManager.GetString("lblCoLoiXayRa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error.
        /// </summary>
        internal static string lblDaCoLoiXayRa {
            get {
                return ResourceManager.GetString("lblDaCoLoiXayRa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string lblDiaChi {
            get {
                return ResourceManager.GetString("lblDiaChi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        internal static string lblDienThoai {
            get {
                return ResourceManager.GetString("lblDienThoai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string lblDong {
            get {
                return ResourceManager.GetString("lblDong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close all.
        /// </summary>
        internal static string lblDongTatCa {
            get {
                return ResourceManager.GetString("lblDongTatCa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string lblDonVi {
            get {
                return ResourceManager.GetString("lblDonVi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superior unit.
        /// </summary>
        internal static string lblDonViCapTren {
            get {
                return ResourceManager.GetString("lblDonViCapTren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit - Department.
        /// </summary>
        internal static string lblDonViPhongBan {
            get {
                return ResourceManager.GetString("lblDonViPhongBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        internal static string lblFax {
            get {
                return ResourceManager.GetString("lblFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string lblHeThong {
            get {
                return ResourceManager.GetString("lblHeThong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string lblHienThi {
            get {
                return ResourceManager.GetString("lblHienThi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string lblLuu {
            get {
                return ResourceManager.GetString("lblLuu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string lblLuuY {
            get {
                return ResourceManager.GetString("lblLuuY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open all.
        /// </summary>
        internal static string lblMoTatCa {
            get {
                return ResourceManager.GetString("lblMoTatCa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date configuration.
        /// </summary>
        internal static string lblNgayCauHinh {
            get {
                return ResourceManager.GetString("lblNgayCauHinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient of the job.
        /// </summary>
        internal static string lblNguoiNhanCV {
            get {
                return ResourceManager.GetString("lblNguoiNhanCV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The recipient of the document.
        /// </summary>
        internal static string lblNguoiNhanVB {
            get {
                return ResourceManager.GetString("lblNguoiNhanVB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the address.
        /// </summary>
        internal static string lblNhapDiaChi {
            get {
                return ResourceManager.GetString("lblNhapDiaChi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retype.
        /// </summary>
        internal static string lblNhapLai {
            get {
                return ResourceManager.GetString("lblNhapLai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the date configuration.
        /// </summary>
        internal static string lblNhapNgayCauhinh {
            get {
                return ResourceManager.GetString("lblNhapNgayCauhinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the telephone.
        /// </summary>
        internal static string lblNhapSoDT {
            get {
                return ResourceManager.GetString("lblNhapSoDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the fax.
        /// </summary>
        internal static string lblNhapSoFax {
            get {
                return ResourceManager.GetString("lblNhapSoFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the order of the numerical type.
        /// </summary>
        internal static string lblNhapSoThuTu {
            get {
                return ResourceManager.GetString("lblNhapSoThuTu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the department name.
        /// </summary>
        internal static string lblNhapTenDonvi {
            get {
                return ResourceManager.GetString("lblNhapTenDonvi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the abbreviations name.
        /// </summary>
        internal static string lblNhapTenVietTat {
            get {
                return ResourceManager.GetString("lblNhapTenVietTat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string lblPhongBan {
            get {
                return ResourceManager.GetString("lblPhongBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort unit.
        /// </summary>
        internal static string lblSapXepDonVi {
            get {
                return ResourceManager.GetString("lblSapXepDonVi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax Number.
        /// </summary>
        internal static string lblSoFax {
            get {
                return ResourceManager.GetString("lblSoFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the submission form.
        /// </summary>
        internal static string lblSuDungPhieuTrinh {
            get {
                return ResourceManager.GetString("lblSuDungPhieuTrinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use document.
        /// </summary>
        internal static string lblSuSungSoVB {
            get {
                return ResourceManager.GetString("lblSuSungSoVB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit name.
        /// </summary>
        internal static string lblTenDonVi {
            get {
                return ResourceManager.GetString("lblTenDonVi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit - Department name.
        /// </summary>
        internal static string lblTenDonViPhongBan {
            get {
                return ResourceManager.GetString("lblTenDonViPhongBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department name.
        /// </summary>
        internal static string lblTenPhongBan {
            get {
                return ResourceManager.GetString("lblTenPhongBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbreviations name.
        /// </summary>
        internal static string lblTenVietTat {
            get {
                return ResourceManager.GetString("lblTenVietTat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add more.
        /// </summary>
        internal static string lblThemLienTiep {
            get {
                return ResourceManager.GetString("lblThemLienTiep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new.
        /// </summary>
        internal static string lblThemMoi {
            get {
                return ResourceManager.GetString("lblThemMoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add unit.
        /// </summary>
        internal static string lblThemMoiDonVi {
            get {
                return ResourceManager.GetString("lblThemMoiDonVi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string lblThoat {
            get {
                return ResourceManager.GetString("lblThoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        internal static string lblThongBao {
            get {
                return ResourceManager.GetString("lblThongBao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordinal.
        /// </summary>
        internal static string lblThuTu {
            get {
                return ResourceManager.GetString("lblThuTu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNIT - DEPARTMENT MANAGEMENT.
        /// </summary>
        internal static string lblTieuDe {
            get {
                return ResourceManager.GetString("lblTieuDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string lblTrangChu {
            get {
                return ResourceManager.GetString("lblTrangChu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string lblTrangThai {
            get {
                return ResourceManager.GetString("lblTrangThai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headquarters.
        /// </summary>
        internal static string lblTruSoChinh {
            get {
                return ResourceManager.GetString("lblTruSoChinh", resourceCulture);
            }
        }
    }
}
