//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LichTrucBanLanhDao {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LichTrucBanLanhDao() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.LichTrucBanLanhDao", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agree.
        /// </summary>
        internal static string btnDongY {
            get {
                return ResourceManager.GetString("btnDongY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        internal static string btnHienTai {
            get {
                return ResourceManager.GetString("btnHienTai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After.
        /// </summary>
        internal static string btnSau {
            get {
                return ResourceManager.GetString("btnSau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before.
        /// </summary>
        internal static string btnTruoc {
            get {
                return ResourceManager.GetString("btnTruoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Word.
        /// </summary>
        internal static string btnXuatWord {
            get {
                return ResourceManager.GetString("btnXuatWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select .
        /// </summary>
        internal static string lblBanChuaChonThoiGianTrucLD {
            get {
                return ResourceManager.GetString("lblBanChuaChonThoiGianTrucLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure delete?.
        /// </summary>
        internal static string lblBanCoChacChanXoa {
            get {
                return ResourceManager.GetString("lblBanCoChacChanXoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pls enter.
        /// </summary>
        internal static string lblBanVuiLongNhapLaiDinhDang {
            get {
                return ResourceManager.GetString("lblBanVuiLongNhapLaiDinhDang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information Required.
        /// </summary>
        internal static string lblBatBuocNhapThongTin {
            get {
                return ResourceManager.GetString("lblBatBuocNhapThongTin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields marked.
        /// </summary>
        internal static string lblCacTruongCoDau {
            get {
                return ResourceManager.GetString("lblCacTruongCoDau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        internal static string lblChiTiet {
            get {
                return ResourceManager.GetString("lblChiTiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select manager.
        /// </summary>
        internal static string lblChonLanhDao {
            get {
                return ResourceManager.GetString("lblChonLanhDao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select month.
        /// </summary>
        internal static string lblChonThang {
            get {
                return ResourceManager.GetString("lblChonThang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select week.
        /// </summary>
        internal static string lblChonTuan {
            get {
                return ResourceManager.GetString("lblChonTuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error !.
        /// </summary>
        internal static string lblCoLoiXayRa {
            get {
                return ResourceManager.GetString("lblCoLoiXayRa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error !.
        /// </summary>
        internal static string lblDaCoLoiXayRa {
            get {
                return ResourceManager.GetString("lblDaCoLoiXayRa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string lblDongLai {
            get {
                return ResourceManager.GetString("lblDongLai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string lblGhiChu {
            get {
                return ResourceManager.GetString("lblGhiChu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        internal static string lblLanhDao {
            get {
                return ResourceManager.GetString("lblLanhDao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zzz.
        /// </summary>
        internal static string lblLichTrucBanGiamDoc {
            get {
                return ResourceManager.GetString("lblLichTrucBanGiamDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zzz.
        /// </summary>
        internal static string lblLichTrucBanGiamDocInHoa {
            get {
                return ResourceManager.GetString("lblLichTrucBanGiamDocInHoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zzz.
        /// </summary>
        internal static string lblLichTrucBanGiamDocThang {
            get {
                return ResourceManager.GetString("lblLichTrucBanGiamDocThang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string lblLuu {
            get {
                return ResourceManager.GetString("lblLuu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        internal static string lblLuuY {
            get {
                return ResourceManager.GetString("lblLuuY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter note.
        /// </summary>
        internal static string lblNhapGhiChu {
            get {
                return ResourceManager.GetString("lblNhapGhiChu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used.
        /// </summary>
        internal static string lblSuDung {
            get {
                return ResourceManager.GetString("lblSuDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jan.
        /// </summary>
        internal static string lblThang1 {
            get {
                return ResourceManager.GetString("lblThang1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oct.
        /// </summary>
        internal static string lblThang10 {
            get {
                return ResourceManager.GetString("lblThang10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nov.
        /// </summary>
        internal static string lblThang11 {
            get {
                return ResourceManager.GetString("lblThang11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dec.
        /// </summary>
        internal static string lblThang12 {
            get {
                return ResourceManager.GetString("lblThang12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feb.
        /// </summary>
        internal static string lblThang2 {
            get {
                return ResourceManager.GetString("lblThang2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        internal static string lblThang3 {
            get {
                return ResourceManager.GetString("lblThang3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        internal static string lblThang4 {
            get {
                return ResourceManager.GetString("lblThang4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        internal static string lblThang5 {
            get {
                return ResourceManager.GetString("lblThang5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        internal static string lblThang6 {
            get {
                return ResourceManager.GetString("lblThang6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        internal static string lblThang7 {
            get {
                return ResourceManager.GetString("lblThang7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aug.
        /// </summary>
        internal static string lblThang8 {
            get {
                return ResourceManager.GetString("lblThang8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sep.
        /// </summary>
        internal static string lblThang9 {
            get {
                return ResourceManager.GetString("lblThang9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add continue.
        /// </summary>
        internal static string lblThemLienTiep {
            get {
                return ResourceManager.GetString("lblThemLienTiep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string lblThemMoi {
            get {
                return ResourceManager.GetString("lblThemMoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zzz.
        /// </summary>
        internal static string lblThemMoiLichTrucBanGiamDoc {
            get {
                return ResourceManager.GetString("lblThemMoiLichTrucBanGiamDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string lblThoat {
            get {
                return ResourceManager.GetString("lblThoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        internal static string lblThongBao {
            get {
                return ResourceManager.GetString("lblThongBao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string lblTrangChu {
            get {
                return ResourceManager.GetString("lblTrangChu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zzz.
        /// </summary>
        internal static string lblTrucLanhDao {
            get {
                return ResourceManager.GetString("lblTrucLanhDao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string lblXoa {
            get {
                return ResourceManager.GetString("lblXoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zzz.
        /// </summary>
        internal static string lblXoaLichTrucBanLanhDao {
            get {
                return ResourceManager.GetString("lblXoaLichTrucBanLanhDao", resourceCulture);
            }
        }
    }
}
