//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LichCaNhan {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LichCaNhan() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.LichCaNhan", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string btnLuu {
            get {
                return ResourceManager.GetString("btnLuu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retype.
        /// </summary>
        internal static string btnNhapLai {
            get {
                return ResourceManager.GetString("btnNhapLai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string btnThoat {
            get {
                return ResourceManager.GetString("btnThoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string btnXoa {
            get {
                return ResourceManager.GetString("btnXoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to information required.
        /// </summary>
        internal static string lblBatBuocNhapThongTin {
            get {
                return ResourceManager.GetString("lblBatBuocNhapThongTin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string lblBatDau {
            get {
                return ResourceManager.GetString("lblBatDau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No fill color.
        /// </summary>
        internal static string lblBoMau {
            get {
                return ResourceManager.GetString("lblBoMau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields marked.
        /// </summary>
        internal static string lblCacTruongCoDau {
            get {
                return ResourceManager.GetString("lblCacTruongCoDau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select event color.
        /// </summary>
        internal static string lblChonMauSuKien {
            get {
                return ResourceManager.GetString("lblChonMauSuKien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error !.
        /// </summary>
        internal static string lblCoLoiXayRa {
            get {
                return ResourceManager.GetString("lblCoLoiXayRa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error !.
        /// </summary>
        internal static string lblDaCoLoiXayRa {
            get {
                return ResourceManager.GetString("lblDaCoLoiXayRa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string lblDiaDiem {
            get {
                return ResourceManager.GetString("lblDiaDiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string lblHomNay {
            get {
                return ResourceManager.GetString("lblHomNay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string lblKetThuc {
            get {
                return ResourceManager.GetString("lblKetThuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal schedule.
        /// </summary>
        internal static string lblLichCaNhan {
            get {
                return ResourceManager.GetString("lblLichCaNhan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string lblLuuY {
            get {
                return ResourceManager.GetString("lblLuuY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string lblMoTa {
            get {
                return ResourceManager.GetString("lblMoTa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter address.
        /// </summary>
        internal static string lblNhapDiaDiem {
            get {
                return ResourceManager.GetString("lblNhapDiaDiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter description.
        /// </summary>
        internal static string lblNhapMoTa {
            get {
                return ResourceManager.GetString("lblNhapMoTa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter titles.
        /// </summary>
        internal static string lblNhapTieuDe {
            get {
                return ResourceManager.GetString("lblNhapTieuDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        internal static string lblNoiDung {
            get {
                return ResourceManager.GetString("lblNoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management personal schedule.
        /// </summary>
        internal static string lblQuanLyLichCaNhan {
            get {
                return ResourceManager.GetString("lblQuanLyLichCaNhan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager&apos;s name.
        /// </summary>
        internal static string lblTenLanhDao {
            get {
                return ResourceManager.GetString("lblTenLanhDao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add continue.
        /// </summary>
        internal static string lblThemLienTiep {
            get {
                return ResourceManager.GetString("lblThemLienTiep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add .
        /// </summary>
        internal static string lblThemMoi {
            get {
                return ResourceManager.GetString("lblThemMoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string lblThoiGian {
            get {
                return ResourceManager.GetString("lblThoiGian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        internal static string lblThongBao {
            get {
                return ResourceManager.GetString("lblThongBao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string lblTieuDe {
            get {
                return ResourceManager.GetString("lblTieuDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string lblTrangChu {
            get {
                return ResourceManager.GetString("lblTrangChu", resourceCulture);
            }
        }
    }
}
