//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Log {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Log() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Log", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string btnDong {
            get {
                return ResourceManager.GetString("btnDong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string btnDongLai {
            get {
                return ResourceManager.GetString("btnDongLai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string btnTimKiem {
            get {
                return ResourceManager.GetString("btnTimKiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export .xls.
        /// </summary>
        internal static string btnXuatExcel {
            get {
                return ResourceManager.GetString("btnXuatExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        internal static string lblAn {
            get {
                return ResourceManager.GetString("lblAn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handover.
        /// </summary>
        internal static string lblBanGiao {
            get {
                return ResourceManager.GetString("lblBanGiao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog.
        /// </summary>
        internal static string lblBienMuc {
            get {
                return ResourceManager.GetString("lblBienMuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string lblCapNhat {
            get {
                return ResourceManager.GetString("lblCapNhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update profile.
        /// </summary>
        internal static string lblCapNhatHoSo {
            get {
                return ResourceManager.GetString("lblCapNhatHoSo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log details.
        /// </summary>
        internal static string lblChiTietLog {
            get {
                return ResourceManager.GetString("lblChiTietLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string lblChon {
            get {
                return ResourceManager.GetString("lblChon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Function.
        /// </summary>
        internal static string lblChonChucNang {
            get {
                return ResourceManager.GetString("lblChonChucNang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Search Scope.
        /// </summary>
        internal static string lblChonPhamViTimKiem {
            get {
                return ResourceManager.GetString("lblChonPhamViTimKiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function.
        /// </summary>
        internal static string lblChucNang {
            get {
                return ResourceManager.GetString("lblChucNang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        internal static string lblChuyenTiep {
            get {
                return ResourceManager.GetString("lblChuyenTiep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To date.
        /// </summary>
        internal static string lblDenNgay {
            get {
                return ResourceManager.GetString("lblDenNgay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change pass.
        /// </summary>
        internal static string lblDoiMatKhau {
            get {
                return ResourceManager.GetString("lblDoiMatKhau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dep/Branch.
        /// </summary>
        internal static string lblDonVi {
            get {
                return ResourceManager.GetString("lblDonVi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give opinion.
        /// </summary>
        internal static string lblDuaYKien {
            get {
                return ResourceManager.GetString("lblDuaYKien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        internal static string lblDuongDan {
            get {
                return ResourceManager.GetString("lblDuongDan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        internal static string lblDuyet {
            get {
                return ResourceManager.GetString("lblDuyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve content and subject .
        /// </summary>
        internal static string lblDuyetTheThuc {
            get {
                return ResourceManager.GetString("lblDuyetTheThuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string lblGui {
            get {
                return ResourceManager.GetString("lblGui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string lblHeThong {
            get {
                return ResourceManager.GetString("lblHeThong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string lblHienThi {
            get {
                return ResourceManager.GetString("lblHienThi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string lblHoanThanh {
            get {
                return ResourceManager.GetString("lblHoanThanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string lblHuyDuyet {
            get {
                return ResourceManager.GetString("lblHuyDuyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string lblID {
            get {
                return ResourceManager.GetString("lblID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP.
        /// </summary>
        internal static string lblIP {
            get {
                return ResourceManager.GetString("lblIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don’t receive.
        /// </summary>
        internal static string lblKhongTiepNhan {
            get {
                return ResourceManager.GetString("lblKhongTiepNhan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Log.
        /// </summary>
        internal static string lblLogNguoiDung {
            get {
                return ResourceManager.GetString("lblLogNguoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string lblNguoiDung {
            get {
                return ResourceManager.GetString("lblNguoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter search keyword.
        /// </summary>
        internal static string lblNhapTuKhoaTimKiem {
            get {
                return ResourceManager.GetString("lblNhapTuKhoaTimKiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        internal static string lblNoiDung {
            get {
                return ResourceManager.GetString("lblNoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The information does not exist in the system!.
        /// </summary>
        internal static string lblNoiDungThongBao {
            get {
                return ResourceManager.GetString("lblNoiDungThongBao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope.
        /// </summary>
        internal static string lblPhamVi {
            get {
                return ResourceManager.GetString("lblPhamVi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string lblTatCa {
            get {
                return ResourceManager.GetString("lblTatCa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operate.
        /// </summary>
        internal static string lblThaoTac {
            get {
                return ResourceManager.GetString("lblThaoTac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        internal static string lblThaoTacThucHien {
            get {
                return ResourceManager.GetString("lblThaoTacThucHien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new.
        /// </summary>
        internal static string lblThemMoi {
            get {
                return ResourceManager.GetString("lblThemMoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new task.
        /// </summary>
        internal static string lblThemMoiCongViec {
            get {
                return ResourceManager.GetString("lblThemMoiCongViec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new document.
        /// </summary>
        internal static string lblThemMoiVanBan {
            get {
                return ResourceManager.GetString("lblThemMoiVanBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string lblThoiGian {
            get {
                return ResourceManager.GetString("lblThoiGian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        internal static string lblThongBao {
            get {
                return ResourceManager.GetString("lblThongBao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive .
        /// </summary>
        internal static string lblTiepNhan {
            get {
                return ResourceManager.GetString("lblTiepNhan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity List.
        /// </summary>
        internal static string lblTieuDe {
            get {
                return ResourceManager.GetString("lblTieuDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zzzz.
        /// </summary>
        internal static string lblTieuHuyVatLy {
            get {
                return ResourceManager.GetString("lblTieuHuyVatLy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in.
        /// </summary>
        internal static string lblTimKiemTrong {
            get {
                return ResourceManager.GetString("lblTimKiemTrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string lblTrangChu {
            get {
                return ResourceManager.GetString("lblTrangChu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Content and Subject.
        /// </summary>
        internal static string lblTrinhTheThuc {
            get {
                return ResourceManager.GetString("lblTrinhTheThuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        internal static string lblTuChoi {
            get {
                return ResourceManager.GetString("lblTuChoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword.
        /// </summary>
        internal static string lblTuKhoa {
            get {
                return ResourceManager.GetString("lblTuKhoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To date.
        /// </summary>
        internal static string lblTuNgay {
            get {
                return ResourceManager.GetString("lblTuNgay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string lblXacNhan {
            get {
                return ResourceManager.GetString("lblXacNhan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string lblXem {
            get {
                return ResourceManager.GetString("lblXem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string lblXoa {
            get {
                return ResourceManager.GetString("lblXoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete task.
        /// </summary>
        internal static string lblXoaCongViec {
            get {
                return ResourceManager.GetString("lblXoaCongViec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete list of selected.
        /// </summary>
        internal static string lblXoaDanhSachDaChon {
            get {
                return ResourceManager.GetString("lblXoaDanhSachDaChon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete document.
        /// </summary>
        internal static string lblXoaVanBan {
            get {
                return ResourceManager.GetString("lblXoaVanBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires.
        /// </summary>
        internal static string lblYeuCau {
            get {
                return ResourceManager.GetString("lblYeuCau", resourceCulture);
            }
        }
    }
}
