//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Notification {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Notification() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Notification", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide selected record.
        /// </summary>
        internal static string lblAnBanGhiDaChon {
            get {
                return ResourceManager.GetString("lblAnBanGhiDaChon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden role.
        /// </summary>
        internal static string lblAnQuyenHan {
            get {
                return ResourceManager.GetString("lblAnQuyenHan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully hiding value categories.
        /// </summary>
        internal static string lblAnThanhCongDanhMucGiaTri {
            get {
                return ResourceManager.GetString("lblAnThanhCongDanhMucGiaTri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden documents category successfully.
        /// </summary>
        internal static string lblAnThanhCongLoaiVanBan {
            get {
                return ResourceManager.GetString("lblAnThanhCongLoaiVanBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hides the meeting room successfully.
        /// </summary>
        internal static string lblAnThanhCongPhongHop {
            get {
                return ResourceManager.GetString("lblAnThanhCongPhongHop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden notification successfully.
        /// </summary>
        internal static string lblAnThanhCongThongBao {
            get {
                return ResourceManager.GetString("lblAnThanhCongThongBao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden print register book successfully.
        /// </summary>
        internal static string lblAnThanhCongVanBan {
            get {
                return ResourceManager.GetString("lblAnThanhCongVanBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not selected attachments.
        /// </summary>
        internal static string lblBanChuaChonFileDinhKem {
            get {
                return ResourceManager.GetString("lblBanChuaChonFileDinhKem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have chosen to hand over the task.
        /// </summary>
        internal static string lblBanDaChonBanGiaoCongViec {
            get {
                return ResourceManager.GetString("lblBanDaChonBanGiaoCongViec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work handover can not be deleted because it is in use.
        /// </summary>
        internal static string lblBanGiaoCongViecKhongXoaDuocDoDangSuDung {
            get {
                return ResourceManager.GetString("lblBanGiaoCongViecKhongXoaDuocDoDangSuDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work reports can not be deleted because they are in use.
        /// </summary>
        internal static string lblBaoCaoCVKhongXoaDuocDoDangSuDung {
            get {
                return ResourceManager.GetString("lblBaoCaoCVKhongXoaDuocDoDangSuDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update handover task successfully.
        /// </summary>
        internal static string lblCapNhatBanGiaoCongViecThanhCong {
            get {
                return ResourceManager.GetString("lblCapNhatBanGiaoCongViecThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update SMS - Email configuration.
        /// </summary>
        internal static string lblCapNhatCauHinhSMSEmail {
            get {
                return ResourceManager.GetString("lblCapNhatCauHinhSMSEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark all as read.
        /// </summary>
        internal static string lblCapNhatDaDoc {
            get {
                return ResourceManager.GetString("lblCapNhatDaDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update read notification successfully.
        /// </summary>
        internal static string lblCapNhatDaDocThongBaoThanhCong {
            get {
                return ResourceManager.GetString("lblCapNhatDaDocThongBaoThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update the value category.
        /// </summary>
        internal static string lblCapNhatDanhMucGiaTri {
            get {
                return ResourceManager.GetString("lblCapNhatDanhMucGiaTri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated meeting room directory.
        /// </summary>
        internal static string lblCapNhatDanhMucPhongHop {
            get {
                return ResourceManager.GetString("lblCapNhatDanhMucPhongHop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update personal calendar successfully.
        /// </summary>
        internal static string lblCapNhatLichCaNhanThanhCong {
            get {
                return ResourceManager.GetString("lblCapNhatLichCaNhanThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated meeting schedule successfully.
        /// </summary>
        internal static string lblCapNhatLichHopCongTacThanhCong {
            get {
                return ResourceManager.GetString("lblCapNhatLichHopCongTacThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update documents category.
        /// </summary>
        internal static string lblCapNhatLoaiVanBan {
            get {
                return ResourceManager.GetString("lblCapNhatLoaiVanBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update successfully.
        /// </summary>
        internal static string lblCapNhatThanhCong {
            get {
                return ResourceManager.GetString("lblCapNhatThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated work reports successfully.
        /// </summary>
        internal static string lblCapNhatThanhCongBaoCaoCongViec {
            get {
                return ResourceManager.GetString("lblCapNhatThanhCongBaoCaoCongViec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful update of work program.
        /// </summary>
        internal static string lblCapNhatThanhCongChuongTrinhCongTac {
            get {
                return ResourceManager.GetString("lblCapNhatThanhCongChuongTrinhCongTac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update role successfully.
        /// </summary>
        internal static string lblCapNhatThanhCongQuyenHan {
            get {
                return ResourceManager.GetString("lblCapNhatThanhCongQuyenHan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update print register book successfully.
        /// </summary>
        internal static string lblCapNhatThanhCongSoVanBan {
            get {
                return ResourceManager.GetString("lblCapNhatThanhCongSoVanBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status update successfully.
        /// </summary>
        internal static string lblCapNhatThanhCongTrangThai {
            get {
                return ResourceManager.GetString("lblCapNhatThanhCongTrangThai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated authorization.
        /// </summary>
        internal static string lblCapNhatThanhCongUyQuyen {
            get {
                return ResourceManager.GetString("lblCapNhatThanhCongUyQuyen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful update role powers.
        /// </summary>
        internal static string lblCapNhatThanhCongVaiTroQuyenHan {
            get {
                return ResourceManager.GetString("lblCapNhatThanhCongVaiTroQuyenHan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update notification.
        /// </summary>
        internal static string lblCapNhatThongBao {
            get {
                return ResourceManager.GetString("lblCapNhatThongBao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update booking information successfully.
        /// </summary>
        internal static string lblCapNhatThongTinDatBaoThanhCong {
            get {
                return ResourceManager.GetString("lblCapNhatThongTinDatBaoThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update order of display successfully.
        /// </summary>
        internal static string lblCapNhatThuTuHienThiThanhCong {
            get {
                return ResourceManager.GetString("lblCapNhatThuTuHienThiThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update the progress of the work program successfully.
        /// </summary>
        internal static string lblCapNhatTienDoCTCTThanhCong {
            get {
                return ResourceManager.GetString("lblCapNhatTienDoCTCTThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update the document goes to the agenda.
        /// </summary>
        internal static string lblCapNhatVanBanDiVaoCTCT {
            get {
                return ResourceManager.GetString("lblCapNhatVanBanDiVaoCTCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update document incoming to the agenda.
        /// </summary>
        internal static string lblCapNhatVanBanVaoCTCT {
            get {
                return ResourceManager.GetString("lblCapNhatVanBanVaoCTCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select function.
        /// </summary>
        internal static string lblChonChucNang {
            get {
                return ResourceManager.GetString("lblChonChucNang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select document category.
        /// </summary>
        internal static string lblChonLoaiVanBan {
            get {
                return ResourceManager.GetString("lblChonLoaiVanBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select search scope.
        /// </summary>
        internal static string lblChonPhamViTimKiem {
            get {
                return ResourceManager.GetString("lblChonPhamViTimKiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function.
        /// </summary>
        internal static string lblChucNang {
            get {
                return ResourceManager.GetString("lblChucNang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information working.
        /// </summary>
        internal static string lblChuongTrinhCongTac {
            get {
                return ResourceManager.GetString("lblChuongTrinhCongTac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program can not be deleted because it is in use.
        /// </summary>
        internal static string lblChuongTrinhCongTacKhongXoaDuoc {
            get {
                return ResourceManager.GetString("lblChuongTrinhCongTacKhongXoaDuoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer approved work program successfully.
        /// </summary>
        internal static string lblChuyenChuongTrinhPheDuyetCongTacThanhCong {
            get {
                return ResourceManager.GetString("lblChuyenChuongTrinhPheDuyetCongTacThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer work program to successful units.
        /// </summary>
        internal static string lblChuyenCTCTDenDonViThanhCong {
            get {
                return ResourceManager.GetString("lblChuyenCTCTDenDonViThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer approved detailed roadmap successfully.
        /// </summary>
        internal static string lblChuyenPheDuyetLoTrinhChiTietThanhCong {
            get {
                return ResourceManager.GetString("lblChuyenPheDuyetLoTrinhChiTietThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear notifications.
        /// </summary>
        internal static string lblClearNotification {
            get {
                return ResourceManager.GetString("lblClearNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error deleting the notification information.
        /// </summary>
        internal static string lblCoLoiTrongViecXoaThongTinThongBao {
            get {
                return ResourceManager.GetString("lblCoLoiTrongViecXoaThongTinThongBao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred.
        /// </summary>
        internal static string lblCoLoiXayRa {
            get {
                return ResourceManager.GetString("lblCoLoiXayRa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        internal static string lblCongViec {
            get {
                return ResourceManager.GetString("lblCongViec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully hidden the role.
        /// </summary>
        internal static string lblDaAnThanhCongVaiTro {
            get {
                return ResourceManager.GetString("lblDaAnThanhCongVaiTro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated role order.
        /// </summary>
        internal static string lblDaCapNhatLaiThuTuVaiTro {
            get {
                return ResourceManager.GetString("lblDaCapNhatLaiThuTuVaiTro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error please review.
        /// </summary>
        internal static string lblDaCoLoiVuiLongXemLai {
            get {
                return ResourceManager.GetString("lblDaCoLoiVuiLongXemLai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was submitted successfully.
        /// </summary>
        internal static string lblDaDuocGuiThanhCong {
            get {
                return ResourceManager.GetString("lblDaDuocGuiThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully displayed role.
        /// </summary>
        internal static string lblDaHienThiThanhCongVaiTro {
            get {
                return ResourceManager.GetString("lblDaHienThiThanhCongVaiTro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading data.
        /// </summary>
        internal static string lblDangTaiDuLieu {
            get {
                return ResourceManager.GetString("lblDangTaiDuLieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluate work successfully.
        /// </summary>
        internal static string lblDanhGiaCongViecThanhCong {
            get {
                return ResourceManager.GetString("lblDanhGiaCongViecThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluate successful work reports.
        /// </summary>
        internal static string lblDanhGiaThanhCongBaoCaoCongViec {
            get {
                return ResourceManager.GetString("lblDanhGiaThanhCongBaoCaoCongViec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value category is currently displayed.
        /// </summary>
        internal static string lblDanhMucGiaTriHienDangHienThi {
            get {
                return ResourceManager.GetString("lblDanhMucGiaTriHienDangHienThi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value category can not be deleted because it is in use.
        /// </summary>
        internal static string lblDanhMucGiaTriKhongXoaDuoc {
            get {
                return ResourceManager.GetString("lblDanhMucGiaTriKhongXoaDuoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category is not deleted as it is in use.
        /// </summary>
        internal static string lblDanhMucKhongXoaDuocDoDangSuDung {
            get {
                return ResourceManager.GetString("lblDanhMucKhongXoaDuocDoDangSuDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of meeting rooms.
        /// </summary>
        internal static string lblDanhMucPhongHop {
            get {
                return ResourceManager.GetString("lblDanhMucPhongHop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The meeting room list can not be deleted because it is in use.
        /// </summary>
        internal static string lblDanhMucPhongHopKhongXoaDuoc {
            get {
                return ResourceManager.GetString("lblDanhMucPhongHopKhongXoaDuoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to already exists.
        /// </summary>
        internal static string lblDaTonTai {
            get {
                return ResourceManager.GetString("lblDaTonTai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification already exists.
        /// </summary>
        internal static string lblDaTonTaiThongBao {
            get {
                return ResourceManager.GetString("lblDaTonTaiThongBao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to already exists in the unit.
        /// </summary>
        internal static string lblDaTonTaiTrongDonVi {
            get {
                return ResourceManager.GetString("lblDaTonTaiTrongDonVi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book meeting room.
        /// </summary>
        internal static string lblDatPhong {
            get {
                return ResourceManager.GetString("lblDatPhong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did not deny the details of the unit success.
        /// </summary>
        internal static string lblDaTuChoiLoTrinhChiTietDonViThanhCong {
            get {
                return ResourceManager.GetString("lblDaTuChoiLoTrinhChiTietDonViThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book car.
        /// </summary>
        internal static string lblDatXe {
            get {
                return ResourceManager.GetString("lblDatXe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted successfully.
        /// </summary>
        internal static string lblDaXoaThanhCong {
            get {
                return ResourceManager.GetString("lblDaXoaThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted work reports successfully.
        /// </summary>
        internal static string lblDaXoaThanhCongBaoCaoCongViec {
            get {
                return ResourceManager.GetString("lblDaXoaThanhCongBaoCaoCongViec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted documents category successfully.
        /// </summary>
        internal static string lblDaXoaThanhCongLoaiVanBan {
            get {
                return ResourceManager.GetString("lblDaXoaThanhCongLoaiVanBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string lblDong {
            get {
                return ResourceManager.GetString("lblDong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The unit does not have a representative to receive the Work Program.
        /// </summary>
        internal static string lblDonViChuaCoNguoiDaiDienNhanCTCT {
            get {
                return ResourceManager.GetString("lblDonViChuaCoNguoiDaiDienNhanCTCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units and departments do not have a representative to receive the work program.
        /// </summary>
        internal static string lblDonViPhongBanChuaCoNguoiDaiDien {
            get {
                return ResourceManager.GetString("lblDonViPhongBanChuaCoNguoiDaiDien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feeback of ​​successful processing.
        /// </summary>
        internal static string lblDuaYKienXuLyThanhCong {
            get {
                return ResourceManager.GetString("lblDuaYKienXuLyThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drafting.
        /// </summary>
        internal static string lblDuThao {
            get {
                return ResourceManager.GetString("lblDuThao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve work program successfully.
        /// </summary>
        internal static string lblDuyetChuongTrinhCongTacThanhCong {
            get {
                return ResourceManager.GetString("lblDuyetChuongTrinhCongTacThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve for a successful extension of your work program.
        /// </summary>
        internal static string lblDuyetYeuCauGiaHanChuongTrinhCTThanhCong {
            get {
                return ResourceManager.GetString("lblDuyetYeuCauGiaHanChuongTrinhCTThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category value.
        /// </summary>
        internal static string lblGiaTriDanhMuc {
            get {
                return ResourceManager.GetString("lblGiaTriDanhMuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category value is currently hidden.
        /// </summary>
        internal static string lblGiaTriDanhMucHienDangAn {
            get {
                return ResourceManager.GetString("lblGiaTriDanhMucHienDangAn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send work report.
        /// </summary>
        internal static string lblGuiBaoCaoCongViec {
            get {
                return ResourceManager.GetString("lblGuiBaoCaoCongViec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit work handover successfully.
        /// </summary>
        internal static string lblGuiThanhCongBanGiaoCongViec {
            get {
                return ResourceManager.GetString("lblGuiThanhCongBanGiaoCongViec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send an authorization successfully.
        /// </summary>
        internal static string lblGuiUyQuyenThanhCong {
            get {
                return ResourceManager.GetString("lblGuiUyQuyenThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing timelines must be greater than or equal to the start date.
        /// </summary>
        internal static string lblHanXuLyPhaiLonHonHoacBangNgayBatDau {
            get {
                return ResourceManager.GetString("lblHanXuLyPhaiLonHonHoacBangNgayBatDau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing time must be greater than start date.
        /// </summary>
        internal static string lblHanXuLyPhaiLonHonNgayBatDau {
            get {
                return ResourceManager.GetString("lblHanXuLyPhaiLonHonNgayBatDau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display role.
        /// </summary>
        internal static string lblHienThiQuyenHan {
            get {
                return ResourceManager.GetString("lblHienThiQuyenHan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully displayed value categories.
        /// </summary>
        internal static string lblHienThiThanhCongDanhMucGiaTri {
            get {
                return ResourceManager.GetString("lblHienThiThanhCongDanhMucGiaTri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show documents category successfully.
        /// </summary>
        internal static string lblHienThiThanhCongLoaiVanBan {
            get {
                return ResourceManager.GetString("lblHienThiThanhCongLoaiVanBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully displaying the meeting room.
        /// </summary>
        internal static string lblHienThiThanhCongPhongHop {
            get {
                return ResourceManager.GetString("lblHienThiThanhCongPhongHop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show print register book successfully.
        /// </summary>
        internal static string lblHienThiThanhCongSoVanBan {
            get {
                return ResourceManager.GetString("lblHienThiThanhCongSoVanBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show notification successfully.
        /// </summary>
        internal static string lblHienThiThanhCongThongBao {
            get {
                return ResourceManager.GetString("lblHienThiThanhCongThongBao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish the work program.
        /// </summary>
        internal static string lblKetThucChuongTrinhCongTac {
            get {
                return ResourceManager.GetString("lblKetThucChuongTrinhCongTac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No role is selected.
        /// </summary>
        internal static string lblKhongCoVaiTroNaoDuocChon {
            get {
                return ResourceManager.GetString("lblKhongCoVaiTroNaoDuocChon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not authorize the account yourself.
        /// </summary>
        internal static string lblKhongTheUyQuyenChoTaiKhoanChinhMinh {
            get {
                return ResourceManager.GetString("lblKhongTheUyQuyenChoTaiKhoanChinhMinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not delete due to a subroutine.
        /// </summary>
        internal static string lblKhongThucHienXoaDoDaCoLoTrinhCon {
            get {
                return ResourceManager.GetString("lblKhongThucHienXoaDoDaCoLoTrinhCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No permissions found.
        /// </summary>
        internal static string lblKhongTimThayThongTinQuyenHan {
            get {
                return ResourceManager.GetString("lblKhongTimThayThongTinQuyenHan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No role in the system.
        /// </summary>
        internal static string lblKhongTonTaiVaiTroTrongHeThong {
            get {
                return ResourceManager.GetString("lblKhongTonTaiVaiTroTrongHeThong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the numerical order of numbers.
        /// </summary>
        internal static string lblKiemTraLaiCacTruongThuTuPhaiSo {
            get {
                return ResourceManager.GetString("lblKiemTraLaiCacTruongThuTuPhaiSo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule of working.
        /// </summary>
        internal static string lblLichLamViec {
            get {
                return ResourceManager.GetString("lblLichLamViec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The calendar does not delete because it is in use.
        /// </summary>
        internal static string lblLichLamViecKhongXoaDuocDoDangSuDung {
            get {
                return ResourceManager.GetString("lblLichLamViecKhongXoaDuocDoDangSuDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents category.
        /// </summary>
        internal static string lblLoaiVanBan {
            get {
                return ResourceManager.GetString("lblLoaiVanBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents category is hidden.
        /// </summary>
        internal static string lblLoaiVanBanDangAn {
            get {
                return ResourceManager.GetString("lblLoaiVanBanDangAn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents category is displayed.
        /// </summary>
        internal static string lblLoaiVanBanDangHienThi {
            get {
                return ResourceManager.GetString("lblLoaiVanBanDangHienThi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document category can not be deleted because it is in use.
        /// </summary>
        internal static string lblLoaiVanBanKhongXoaDuocDoDangSuDung {
            get {
                return ResourceManager.GetString("lblLoaiVanBanKhongXoaDuocDoDangSuDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! The start time can not be longer than the end time.
        /// </summary>
        internal static string lblLoiThoiGianBatDauPhaiLonHonThoiGianKetThuc {
            get {
                return ResourceManager.GetString("lblLoiThoiGianBatDauPhaiLonHonThoiGianKetThuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed roadmap does not exist.
        /// </summary>
        internal static string lblLoTrinhChiTietKhongTonTai {
            get {
                return ResourceManager.GetString("lblLoTrinhChiTietKhongTonTai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route of work.
        /// </summary>
        internal static string lblLoTrinhCongTac {
            get {
                return ResourceManager.GetString("lblLoTrinhCongTac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one report per quarter!.
        /// </summary>
        internal static string lblMoiQuyChiDuocGuiMotBaoCao {
            get {
                return ResourceManager.GetString("lblMoiQuyChiDuocGuiMotBaoCao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one report per quarter!.
        /// </summary>
        internal static string lblMoiQuyChiDuocTaoMotBaoCao {
            get {
                return ResourceManager.GetString("lblMoiQuyChiDuocTaoMotBaoCao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one report per month!.
        /// </summary>
        internal static string lblMoiThangChiDuocGuiMotBaoCao {
            get {
                return ResourceManager.GetString("lblMoiThangChiDuocGuiMotBaoCao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one report per month is generated!.
        /// </summary>
        internal static string lblMoiThangChiDuocTaoMotBaoCao {
            get {
                return ResourceManager.GetString("lblMoiThangChiDuocTaoMotBaoCao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one report per week!.
        /// </summary>
        internal static string lblMoiTuanChiDuocGuiMotBaoCao {
            get {
                return ResourceManager.GetString("lblMoiTuanChiDuocGuiMotBaoCao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one report per week is generated!.
        /// </summary>
        internal static string lblMoiTuanChiDuocTaoMotBaoCao {
            get {
                return ResourceManager.GetString("lblMoiTuanChiDuocTaoMotBaoCao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date of the child route must be within the timeframe of the parenting route.
        /// </summary>
        internal static string lblNgayThangLoTrinhConPhaiNamTrong {
            get {
                return ResourceManager.GetString("lblNgayThangLoTrinhConPhaiNamTrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input search keywords.
        /// </summary>
        internal static string lblNhapTuKhoaTimKiem {
            get {
                return ResourceManager.GetString("lblNhapTuKhoaTimKiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        internal static string lblNoiDung {
            get {
                return ResourceManager.GetString("lblNoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope.
        /// </summary>
        internal static string lblPhamVi {
            get {
                return ResourceManager.GetString("lblPhamVi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting rooms are currently hidden or in use.
        /// </summary>
        internal static string lblPhongHopHienDangAn {
            get {
                return ResourceManager.GetString("lblPhongHopHienDangAn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting rooms are now displayed.
        /// </summary>
        internal static string lblPhongHopHienDangHienThi {
            get {
                return ResourceManager.GetString("lblPhongHopHienDangHienThi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string lblQuyenHan {
            get {
                return ResourceManager.GetString("lblQuyenHan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorizations can not be deleted because they are in use.
        /// </summary>
        internal static string lblQuyenHanKhongXoaDuocDoDangSuDung {
            get {
                return ResourceManager.GetString("lblQuyenHanKhongXoaDuocDoDangSuDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print register book.
        /// </summary>
        internal static string lblSoVanBan {
            get {
                return ResourceManager.GetString("lblSoVanBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print register book are currently display.
        /// </summary>
        internal static string lblSoVanBanDangHienThi {
            get {
                return ResourceManager.GetString("lblSoVanBanDangHienThi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The print register book already exists.
        /// </summary>
        internal static string lblSoVanBanDaTonTai {
            get {
                return ResourceManager.GetString("lblSoVanBanDaTonTai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print register book are currently hidden.
        /// </summary>
        internal static string lblSoVanBanHienDangAn {
            get {
                return ResourceManager.GetString("lblSoVanBanHienDangAn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print register book are not deleted as they are in use.
        /// </summary>
        internal static string lblSoVanBanKhongXoaDuocDoDangSuDung {
            get {
                return ResourceManager.GetString("lblSoVanBanKhongXoaDuocDoDangSuDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        internal static string lblSTT {
            get {
                return ResourceManager.GetString("lblSTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account does not have permission to update roles.
        /// </summary>
        internal static string lblTaiKhoanCuaBanKhongCoQuyenCapNhatVaiTro {
            get {
                return ResourceManager.GetString("lblTaiKhoanCuaBanKhongCoQuyenCapNhatVaiTro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to successfully.
        /// </summary>
        internal static string lblThanhCong {
            get {
                return ResourceManager.GetString("lblThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new handover task successfully.
        /// </summary>
        internal static string lblThemMoiBanGiaoCongViecThanhCong {
            get {
                return ResourceManager.GetString("lblThemMoiBanGiaoCongViecThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new SMS - Email configuration.
        /// </summary>
        internal static string lblThemMoiCauHinhSMSEmail {
            get {
                return ResourceManager.GetString("lblThemMoiCauHinhSMSEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new value categories.
        /// </summary>
        internal static string lblThemMoiDanhMucGiaTri {
            get {
                return ResourceManager.GetString("lblThemMoiDanhMucGiaTri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new meeting room list.
        /// </summary>
        internal static string lblThemMoiDanhMucPhongHop {
            get {
                return ResourceManager.GetString("lblThemMoiDanhMucPhongHop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new personal calendar successfully.
        /// </summary>
        internal static string lblThemMoiLichCaNhanThanhCong {
            get {
                return ResourceManager.GetString("lblThemMoiLichCaNhanThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new weekly meeting schedule for success.
        /// </summary>
        internal static string lblThemMoiLichHopCongTacTuanThanhCong {
            get {
                return ResourceManager.GetString("lblThemMoiLichHopCongTacTuanThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new documents category.
        /// </summary>
        internal static string lblThemMoiLoaiVanBan {
            get {
                return ResourceManager.GetString("lblThemMoiLoaiVanBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new work report successfully.
        /// </summary>
        internal static string lblThemMoiThanhCongBaoCaoCongViec {
            get {
                return ResourceManager.GetString("lblThemMoiThanhCongBaoCaoCongViec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new work program successfully.
        /// </summary>
        internal static string lblThemMoiThanhCongChuongTrinhCongTac {
            get {
                return ResourceManager.GetString("lblThemMoiThanhCongChuongTrinhCongTac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added a new detailed route.
        /// </summary>
        internal static string lblThemMoiThanhCongLoTrinhChiTiet {
            get {
                return ResourceManager.GetString("lblThemMoiThanhCongLoTrinhChiTiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new role successfully.
        /// </summary>
        internal static string lblThemMoiThanhCongQuyenHan {
            get {
                return ResourceManager.GetString("lblThemMoiThanhCongQuyenHan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new print register book successfully.
        /// </summary>
        internal static string lblthemMoiThanhCongSoVanBan {
            get {
                return ResourceManager.GetString("lblthemMoiThanhCongSoVanBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new state successfully.
        /// </summary>
        internal static string lblThemMoiThanhCongTrangThai {
            get {
                return ResourceManager.GetString("lblThemMoiThanhCongTrangThai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new role successfully.
        /// </summary>
        internal static string lblThemMoiThanhCongVaiTro {
            get {
                return ResourceManager.GetString("lblThemMoiThanhCongVaiTro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new notification.
        /// </summary>
        internal static string lblThemMoiThongBao {
            get {
                return ResourceManager.GetString("lblThemMoiThongBao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new booking information successfully.
        /// </summary>
        internal static string lblThemMoiThongTinDatBaoThanhCong {
            get {
                return ResourceManager.GetString("lblThemMoiThongTinDatBaoThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new authorization successfully.
        /// </summary>
        internal static string lblThemMoiUyQuyenThanhCong {
            get {
                return ResourceManager.GetString("lblThemMoiUyQuyenThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new comments for successfully.
        /// </summary>
        internal static string lblThemMoiYKienThanhCong {
            get {
                return ResourceManager.GetString("lblThemMoiYKienThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string lblThoiGian {
            get {
                return ResourceManager.GetString("lblThoiGian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start time must be less than the end time. Please retype.
        /// </summary>
        internal static string lblThoiGianBDPhaiNhoHonThoiGianKT {
            get {
                return ResourceManager.GetString("lblThoiGianBDPhaiNhoHonThoiGianKT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        internal static string lblThongBaoCuaBan {
            get {
                return ResourceManager.GetString("lblThongBaoCuaBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications are currently hidden.
        /// </summary>
        internal static string lblThongBaoHienDangAn {
            get {
                return ResourceManager.GetString("lblThongBaoHienDangAn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications are currently display.
        /// </summary>
        internal static string lblThongBaoHienDangHienThi {
            get {
                return ResourceManager.GetString("lblThongBaoHienDangHienThi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications are not deleted as they are in use.
        /// </summary>
        internal static string lblThongBaoKhongXoaDuocDoDangSuDung {
            get {
                return ResourceManager.GetString("lblThongBaoKhongXoaDuocDoDangSuDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recirculation successfully.
        /// </summary>
        internal static string lblThuHoiLuanChuyenThanhCong {
            get {
                return ResourceManager.GetString("lblThuHoiLuanChuyenThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject the authorization successfully.
        /// </summary>
        internal static string lblThuHoiUyQuyenThanhCong {
            get {
                return ResourceManager.GetString("lblThuHoiUyQuyenThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order must be a number.
        /// </summary>
        internal static string lblThuTuPhaiLaSo {
            get {
                return ResourceManager.GetString("lblThuTuPhaiLaSo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string lblTimKiem {
            get {
                return ResourceManager.GetString("lblTimKiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in.
        /// </summary>
        internal static string lblTimKiemTrong {
            get {
                return ResourceManager.GetString("lblTimKiemTrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return a successful work report.
        /// </summary>
        internal static string lblTraLaiBaoCaoCongViecThanhCong {
            get {
                return ResourceManager.GetString("lblTraLaiBaoCaoCongViecThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return successful work program.
        /// </summary>
        internal static string lblTraLaiThanhCongCTCT {
            get {
                return ResourceManager.GetString("lblTraLaiThanhCongCTCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string lblTrangChu {
            get {
                return ResourceManager.GetString("lblTrangChu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status already exists.
        /// </summary>
        internal static string lblTrangThaiDaTonTai {
            get {
                return ResourceManager.GetString("lblTrangThaiDaTonTai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The status is not deleted because it is in use.
        /// </summary>
        internal static string lblTrangThaiKhongXoaDuocDoDangSuDung {
            get {
                return ResourceManager.GetString("lblTrangThaiKhongXoaDuocDoDangSuDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject to approve the successful work program.
        /// </summary>
        internal static string lblTuChoiPheDuyetChuongTrinhCongTacThanhCong {
            get {
                return ResourceManager.GetString("lblTuChoiPheDuyetChuongTrinhCongTacThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject request for successful extension of work program.
        /// </summary>
        internal static string lblTuChoiYeuCauGiaHanCTCTThanhCong {
            get {
                return ResourceManager.GetString("lblTuChoiYeuCauGiaHanCTCTThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword.
        /// </summary>
        internal static string lblTuKhoa {
            get {
                return ResourceManager.GetString("lblTuKhoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization failed to delete due to being in use.
        /// </summary>
        internal static string lblUyQuyenKhongXoaDuocDoDangSuDung {
            get {
                return ResourceManager.GetString("lblUyQuyenKhongXoaDuocDoDangSuDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string lblVaiTro {
            get {
                return ResourceManager.GetString("lblVaiTro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The role has been hidden.
        /// </summary>
        internal static string lblVaiTroDaAn {
            get {
                return ResourceManager.GetString("lblVaiTroDaAn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role shown.
        /// </summary>
        internal static string lblVaiTroDaHienThi {
            get {
                return ResourceManager.GetString("lblVaiTroDaHienThi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role can not be erased due to being in use.
        /// </summary>
        internal static string lblVaiTroKhongXoaDuocDoDangSuDung {
            get {
                return ResourceManager.GetString("lblVaiTroKhongXoaDuocDoDangSuDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming documents.
        /// </summary>
        internal static string lblVanBanDen {
            get {
                return ResourceManager.GetString("lblVanBanDen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferring out documents.
        /// </summary>
        internal static string lblVanBanDi {
            get {
                return ResourceManager.GetString("lblVanBanDi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected list.
        /// </summary>
        internal static string lblXoaDanhSachDaChon {
            get {
                return ResourceManager.GetString("lblXoaDanhSachDaChon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted detailed route.
        /// </summary>
        internal static string lblXoaThanhCongLoTrinhChiTiet {
            get {
                return ResourceManager.GetString("lblXoaThanhCongLoTrinhChiTiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete notification successfully.
        /// </summary>
        internal static string lblXoaThongBaoThanhCong {
            get {
                return ResourceManager.GetString("lblXoaThongBaoThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handle the petition.
        /// </summary>
        internal static string lblXuLyKienNghi {
            get {
                return ResourceManager.GetString("lblXuLyKienNghi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request for extension of work program .
        /// </summary>
        internal static string lblYeuCauGiaHanChuongTrinhCT {
            get {
                return ResourceManager.GetString("lblYeuCauGiaHanChuongTrinhCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request to remake successfully.
        /// </summary>
        internal static string lblYeuCauLamLaiThanhCong {
            get {
                return ResourceManager.GetString("lblYeuCauLamLaiThanhCong", resourceCulture);
            }
        }
    }
}
