//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TaiKhoan {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TaiKhoan() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.TaiKhoan", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide list of selected.
        /// </summary>
        internal static string lblAnDanhSachDaChon {
            get {
                return ResourceManager.GetString("lblAnDanhSachDaChon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile&apos;s picture.
        /// </summary>
        internal static string lblAnhDaiDien {
            get {
                return ResourceManager.GetString("lblAnhDaiDien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select title.
        /// </summary>
        internal static string lblBanChuaChonVaiTroChoChucVu {
            get {
                return ResourceManager.GetString("lblBanChuaChonVaiTroChoChucVu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leadership.
        /// </summary>
        internal static string lblBanLanhDao {
            get {
                return ResourceManager.GetString("lblBanLanhDao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senior Leadership.
        /// </summary>
        internal static string lblBanLanhDaoCapCao {
            get {
                return ResourceManager.GetString("lblBanLanhDaoCapCao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information required.
        /// </summary>
        internal static string lblBatBuocNhapThongTin {
            get {
                return ResourceManager.GetString("lblBatBuocNhapThongTin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields marked.
        /// </summary>
        internal static string lblCacTruongCoDau {
            get {
                return ResourceManager.GetString("lblCacTruongCoDau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal.
        /// </summary>
        internal static string lblCaNhan {
            get {
                return ResourceManager.GetString("lblCaNhan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string lblCapNhat {
            get {
                return ResourceManager.GetString("lblCapNhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update user pass.
        /// </summary>
        internal static string lblCapNhatMatKhauNguoiDung {
            get {
                return ResourceManager.GetString("lblCapNhatMatKhauNguoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update user.
        /// </summary>
        internal static string lblCapNhatNguoiDung {
            get {
                return ResourceManager.GetString("lblCapNhatNguoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update user permission.
        /// </summary>
        internal static string lblCapNhatQuyenChoNguoiDung {
            get {
                return ResourceManager.GetString("lblCapNhatQuyenChoNguoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update job role permission.
        /// </summary>
        internal static string lblCapNhatQuyenChoVaiTro {
            get {
                return ResourceManager.GetString("lblCapNhatQuyenChoVaiTro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Information.
        /// </summary>
        internal static string lblCapNhatThongTin {
            get {
                return ResourceManager.GetString("lblCapNhatThongTin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upade role for job title.
        /// </summary>
        internal static string lblCapNhatVaiTroChoChucVu {
            get {
                return ResourceManager.GetString("lblCapNhatVaiTroChoChucVu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config user role.
        /// </summary>
        internal static string lblCauHinhVaiTroNguoiDung {
            get {
                return ResourceManager.GetString("lblCauHinhVaiTroNguoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        internal static string lblChiaSe {
            get {
                return ResourceManager.GetString("lblChiaSe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail Job title .
        /// </summary>
        internal static string lblChiTietChucVu {
            get {
                return ResourceManager.GetString("lblChiTietChucVu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail from - to.
        /// </summary>
        internal static string lblChiTietCoQuanGuiNhan {
            get {
                return ResourceManager.GetString("lblChiTietCoQuanGuiNhan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail document category.
        /// </summary>
        internal static string lblChiTietLoaiVanBan {
            get {
                return ResourceManager.GetString("lblChiTietLoaiVanBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail User group .
        /// </summary>
        internal static string lblChiTietNhomNguoiDung {
            get {
                return ResourceManager.GetString("lblChiTietNhomNguoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail Register books.
        /// </summary>
        internal static string lblChiTietSoVanBan {
            get {
                return ResourceManager.GetString("lblChiTietSoVanBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string lblChon {
            get {
                return ResourceManager.GetString("lblChon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select profile picture.
        /// </summary>
        internal static string lblChonAnhDaiDien {
            get {
                return ResourceManager.GetString("lblChonAnhDaiDien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select other picture.
        /// </summary>
        internal static string lblChonAnhKhac {
            get {
                return ResourceManager.GetString("lblChonAnhKhac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Job Title.
        /// </summary>
        internal static string lblChonChucDanh {
            get {
                return ResourceManager.GetString("lblChonChucDanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Function.
        /// </summary>
        internal static string lblChonChucNang {
            get {
                return ResourceManager.GetString("lblChonChucNang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Used Function.
        /// </summary>
        internal static string lblChonChucNangSuDung {
            get {
                return ResourceManager.GetString("lblChonChucNangSuDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Dept/Branch.
        /// </summary>
        internal static string lblChonDonVi {
            get {
                return ResourceManager.GetString("lblChonDonVi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Dept/Branch.
        /// </summary>
        internal static string lblChonDonViPhongBan {
            get {
                return ResourceManager.GetString("lblChonDonViPhongBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select category.
        /// </summary>
        internal static string lblChonLoai {
            get {
                return ResourceManager.GetString("lblChonLoai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select document category.
        /// </summary>
        internal static string lblChonLoaiVanBan {
            get {
                return ResourceManager.GetString("lblChonLoaiVanBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select User.
        /// </summary>
        internal static string lblChonNguoiDung {
            get {
                return ResourceManager.GetString("lblChonNguoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select address.
        /// </summary>
        internal static string lblChonNoiNhan {
            get {
                return ResourceManager.GetString("lblChonNoiNhan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select search scope.
        /// </summary>
        internal static string lblChonPhamViTimKiem {
            get {
                return ResourceManager.GetString("lblChonPhamViTimKiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string lblChonTatCaDonVi {
            get {
                return ResourceManager.GetString("lblChonTatCaDonVi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        internal static string lblChonTatCaNguoiDung {
            get {
                return ResourceManager.GetString("lblChonTatCaNguoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string lblChonTatCaPhongBan {
            get {
                return ResourceManager.GetString("lblChonTatCaPhongBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Job Title.
        /// </summary>
        internal static string lblChonViTriCongTac {
            get {
                return ResourceManager.GetString("lblChonViTriCongTac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zzzz.
        /// </summary>
        internal static string lblChuanHoa {
            get {
                return ResourceManager.GetString("lblChuanHoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job title.
        /// </summary>
        internal static string lblChucDanh {
            get {
                return ResourceManager.GetString("lblChucDanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function.
        /// </summary>
        internal static string lblChucNang {
            get {
                return ResourceManager.GetString("lblChucNang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        internal static string lblChuyenVien {
            get {
                return ResourceManager.GetString("lblChuyenVien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string lblCo {
            get {
                return ResourceManager.GetString("lblCo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        internal static string lblCoLoiXayRa {
            get {
                return ResourceManager.GetString("lblCoLoiXayRa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From / To.
        /// </summary>
        internal static string lblCoQuanGuiNhan {
            get {
                return ResourceManager.GetString("lblCoQuanGuiNhan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        internal static string lblDaCoLoiXayRa {
            get {
                return ResourceManager.GetString("lblDaCoLoiXayRa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string lblDangTai {
            get {
                return ResourceManager.GetString("lblDangTai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User list.
        /// </summary>
        internal static string lblDanhSachNguoiDungTrong {
            get {
                return ResourceManager.GetString("lblDanhSachNguoiDungTrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of user groups.
        /// </summary>
        internal static string lblDanhSachNhomNguoiDung {
            get {
                return ResourceManager.GetString("lblDanhSachNhomNguoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already exists! Please select another file.
        /// </summary>
        internal static string lblDaTonTaiChonFileKhac {
            get {
                return ResourceManager.GetString("lblDaTonTaiChonFileKhac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set picture default .
        /// </summary>
        internal static string lblDatVeAnhMacDinh {
            get {
                return ResourceManager.GetString("lblDatVeAnhMacDinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string lblDiaChi {
            get {
                return ResourceManager.GetString("lblDiaChi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string lblDiDong {
            get {
                return ResourceManager.GetString("lblDiDong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string lblDoiMatKhau {
            get {
                return ResourceManager.GetString("lblDoiMatKhau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string lblDongLai {
            get {
                return ResourceManager.GetString("lblDongLai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close all.
        /// </summary>
        internal static string lblDongTatCa {
            get {
                return ResourceManager.GetString("lblDongTatCa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close all window.
        /// </summary>
        internal static string lblDongTatCaCacNhanh {
            get {
                return ResourceManager.GetString("lblDongTatCaCacNhanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dept/Branch.
        /// </summary>
        internal static string lblDonVi {
            get {
                return ResourceManager.GetString("lblDonVi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dept/Branch/Group/ Represent.
        /// </summary>
        internal static string lblDonViNhomDaiDien {
            get {
                return ResourceManager.GetString("lblDonViNhomDaiDien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dept/Branch.
        /// </summary>
        internal static string lblDonViPhongBan {
            get {
                return ResourceManager.GetString("lblDonViPhongBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dept/Branch use.
        /// </summary>
        internal static string lblDonViSuDung {
            get {
                return ResourceManager.GetString("lblDonViSuDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used by.
        /// </summary>
        internal static string lblDonViSuDungNhomNguoiDung {
            get {
                return ResourceManager.GetString("lblDonViSuDungNhomNguoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is only used alphabet, numbers, underline and a dot.
        /// </summary>
        internal static string lblEmailChiDuocDungChuCai {
            get {
                return ResourceManager.GetString("lblEmailChiDuocDungChuCai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email wrong format, please check again.
        /// </summary>
        internal static string lblEmailKhongDungDinhDang {
            get {
                return ResourceManager.GetString("lblEmailKhongDungDinhDang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string lblGioiTinh {
            get {
                return ResourceManager.GetString("lblGioiTinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System .
        /// </summary>
        internal static string lblHeThong {
            get {
                return ResourceManager.GetString("lblHeThong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show list of selected.
        /// </summary>
        internal static string lblHienThiDanhSachDaChon {
            get {
                return ResourceManager.GetString("lblHienThiDanhSachDaChon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Last name.
        /// </summary>
        internal static string lblHo {
            get {
                return ResourceManager.GetString("lblHo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zzzz.
        /// </summary>
        internal static string lblKhoiPhongBanDonVi {
            get {
                return ResourceManager.GetString("lblKhoiPhongBanDonVi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string lblKhong {
            get {
                return ResourceManager.GetString("lblKhong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No result .
        /// </summary>
        internal static string lblKhongCoKetQua {
            get {
                return ResourceManager.GetString("lblKhongCoKetQua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zzzz.
        /// </summary>
        internal static string lblKyThuaLenh {
            get {
                return ResourceManager.GetString("lblKyThuaLenh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        internal static string lblLaLanhDao {
            get {
                return ResourceManager.GetString("lblLaLanhDao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager branch.
        /// </summary>
        internal static string lblLanhDaoDonVi {
            get {
                return ResourceManager.GetString("lblLanhDaoDonVi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head of Office.
        /// </summary>
        internal static string lblLanhDaoHanhChinh {
            get {
                return ResourceManager.GetString("lblLanhDaoHanhChinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager Dept.
        /// </summary>
        internal static string lblLanhDaoPhongBan {
            get {
                return ResourceManager.GetString("lblLanhDaoPhongBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head of Office.
        /// </summary>
        internal static string lblLanhDaoVanPhong {
            get {
                return ResourceManager.GetString("lblLanhDaoVanPhong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Register.
        /// </summary>
        internal static string lblLaSoMat {
            get {
                return ResourceManager.GetString("lblLaSoMat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string lblLoai {
            get {
                return ResourceManager.GetString("lblLoai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document category.
        /// </summary>
        internal static string lblLoaiVanBan {
            get {
                return ResourceManager.GetString("lblLoaiVanBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category (ID/ TOD).
        /// </summary>
        internal static string lblLoaiVBDenVBDi {
            get {
                return ResourceManager.GetString("lblLoaiVBDenVBDi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string lblLuu {
            get {
                return ResourceManager.GetString("lblLuu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        internal static string lblLuuY {
            get {
                return ResourceManager.GetString("lblLuuY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass.
        /// </summary>
        internal static string lblMatKhau {
            get {
                return ResourceManager.GetString("lblMatKhau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass contains minimum 8 characters including regular characters, special characters and numbers.
        /// </summary>
        internal static string lblMatKhauCoItNhat {
            get {
                return ResourceManager.GetString("lblMatKhauCoItNhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass does not match, Pls retype !.
        /// </summary>
        internal static string lblMatKhauNhapLaiPhaiTrung {
            get {
                return ResourceManager.GetString("lblMatKhauNhapLaiPhaiTrung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must have special characters such as !@#.
        /// </summary>
        internal static string lblMatKhauPhaiCoKiTuDacBiet {
            get {
                return ResourceManager.GetString("lblMatKhauPhaiCoKiTuDacBiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string lblMoTa {
            get {
                return ResourceManager.GetString("lblMoTa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open All.
        /// </summary>
        internal static string lblMoTatCa {
            get {
                return ResourceManager.GetString("lblMoTatCa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open All.
        /// </summary>
        internal static string lblMoTatCaCacNhanh {
            get {
                return ResourceManager.GetString("lblMoTatCaCacNhanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string lblNam {
            get {
                return ResourceManager.GetString("lblNam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string lblNgayHienThi {
            get {
                return ResourceManager.GetString("lblNgayHienThi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Date.
        /// </summary>
        internal static string lblNgayLuong {
            get {
                return ResourceManager.GetString("lblNgayLuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        internal static string lblNgaySinh {
            get {
                return ResourceManager.GetString("lblNgaySinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth invalid, Pls check again!.
        /// </summary>
        internal static string lblNgaySinhKhongDung {
            get {
                return ResourceManager.GetString("lblNgaySinhKhongDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string lblNguoiDung {
            get {
                return ResourceManager.GetString("lblNguoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User.
        /// </summary>
        internal static string lblNguoiDungKhongTonTaiTrongHT {
            get {
                return ResourceManager.GetString("lblNguoiDungKhongTonTaiTrongHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator.
        /// </summary>
        internal static string lblNguoiTao {
            get {
                return ResourceManager.GetString("lblNguoiTao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator/ User group details.
        /// </summary>
        internal static string lblNguoiTaoChiTietNhomNguoiDung {
            get {
                return ResourceManager.GetString("lblNguoiTaoChiTietNhomNguoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Email.
        /// </summary>
        internal static string lblNhanEmail {
            get {
                return ResourceManager.GetString("lblNhanEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow SMS.
        /// </summary>
        internal static string lblNhanSMS {
            get {
                return ResourceManager.GetString("lblNhanSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Address.
        /// </summary>
        internal static string lblNhapDiaChi {
            get {
                return ResourceManager.GetString("lblNhapDiaChi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Email.
        /// </summary>
        internal static string lblNhapEmail {
            get {
                return ResourceManager.GetString("lblNhapEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retype.
        /// </summary>
        internal static string lblNhapLai {
            get {
                return ResourceManager.GetString("lblNhapLai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retype your pass.
        /// </summary>
        internal static string lblNhapLaiMatKhau {
            get {
                return ResourceManager.GetString("lblNhapLaiMatKhau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your pass.
        /// </summary>
        internal static string lblNhapMatKhau {
            get {
                return ResourceManager.GetString("lblNhapMatKhau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter description.
        /// </summary>
        internal static string lblNhapMoTa {
            get {
                return ResourceManager.GetString("lblNhapMoTa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter birthday.
        /// </summary>
        internal static string lblNhapNgaySinh {
            get {
                return ResourceManager.GetString("lblNhapNgaySinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter phone.
        /// </summary>
        internal static string lblNhapSoDiDong {
            get {
                return ResourceManager.GetString("lblNhapSoDiDong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Tel.
        /// </summary>
        internal static string lblNhapSoDienThoai {
            get {
                return ResourceManager.GetString("lblNhapSoDienThoai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter No..
        /// </summary>
        internal static string lblNhapSoThuTu {
            get {
                return ResourceManager.GetString("lblNhapSoThuTu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Job Title.
        /// </summary>
        internal static string lblNhapTenChucDanh {
            get {
                return ResourceManager.GetString("lblNhapTenChucDanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter company name.
        /// </summary>
        internal static string lblNhapTenCoQuan {
            get {
                return ResourceManager.GetString("lblNhapTenCoQuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter company name sent to.
        /// </summary>
        internal static string lblNhapTenCoQuanDonViGuiDen {
            get {
                return ResourceManager.GetString("lblNhapTenCoQuanDonViGuiDen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a display name.
        /// </summary>
        internal static string lblNhapTenHienThi {
            get {
                return ResourceManager.GetString("lblNhapTenHienThi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter document category name.
        /// </summary>
        internal static string lblNhapTenLoaiVanBan {
            get {
                return ResourceManager.GetString("lblNhapTenLoaiVanBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter user group name.
        /// </summary>
        internal static string lblNhapTenNhomNguoiDung {
            get {
                return ResourceManager.GetString("lblNhapTenNhomNguoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter receive name.
        /// </summary>
        internal static string lblNhapTenNoiNhan {
            get {
                return ResourceManager.GetString("lblNhapTenNoiNhan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter register books name.
        /// </summary>
        internal static string lblNhapTenSoVanBan {
            get {
                return ResourceManager.GetString("lblNhapTenSoVanBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter username.
        /// </summary>
        internal static string lblNhapTenTruyCap {
            get {
                return ResourceManager.GetString("lblNhapTenTruyCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Role name.
        /// </summary>
        internal static string lblNhapTenVaiTro {
            get {
                return ResourceManager.GetString("lblNhapTenVaiTro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter short name.
        /// </summary>
        internal static string lblNhapTenVietTat {
            get {
                return ResourceManager.GetString("lblNhapTenVietTat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter No..
        /// </summary>
        internal static string lblNhapThuTu {
            get {
                return ResourceManager.GetString("lblNhapThuTu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter display No..
        /// </summary>
        internal static string lblNhapThuTuHienThi {
            get {
                return ResourceManager.GetString("lblNhapThuTuHienThi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter search keyword.
        /// </summary>
        internal static string lblNhapTuKhoaTimKiem {
            get {
                return ResourceManager.GetString("lblNhapTuKhoaTimKiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the folder scan.
        /// </summary>
        internal static string lblNhapVaoThuMucScan {
            get {
                return ResourceManager.GetString("lblNhapVaoThuMucScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User group.
        /// </summary>
        internal static string lblNhomNguoiDung {
            get {
                return ResourceManager.GetString("lblNhomNguoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string lblNu {
            get {
                return ResourceManager.GetString("lblNu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope.
        /// </summary>
        internal static string lblPhamVi {
            get {
                return ResourceManager.GetString("lblPhamVi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Job Title .
        /// </summary>
        internal static string lblQuanLyChucDanh {
            get {
                return ResourceManager.GetString("lblQuanLyChucDanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management From / To.
        /// </summary>
        internal static string lblQuanLyCoQuanGuiNhan {
            get {
                return ResourceManager.GetString("lblQuanLyCoQuanGuiNhan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Document category.
        /// </summary>
        internal static string lblQuanLyLoaiVanBan {
            get {
                return ResourceManager.GetString("lblQuanLyLoaiVanBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management user.
        /// </summary>
        internal static string lblQuanLyNguoiDung {
            get {
                return ResourceManager.GetString("lblQuanLyNguoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management user group.
        /// </summary>
        internal static string lblQuanLyNhomNguoiDung {
            get {
                return ResourceManager.GetString("lblQuanLyNhomNguoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Register books.
        /// </summary>
        internal static string lblQuanLySoVanBan {
            get {
                return ResourceManager.GetString("lblQuanLySoVanBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management System Roles .
        /// </summary>
        internal static string lblQuanLyVaiTroHeThong {
            get {
                return ResourceManager.GetString("lblQuanLyVaiTroHeThong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission.
        /// </summary>
        internal static string lblQuyenHan {
            get {
                return ResourceManager.GetString("lblQuyenHan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Branch/Dept.
        /// </summary>
        internal static string lblSoDenDonViPhongBan {
            get {
                return ResourceManager.GetString("lblSoDenDonViPhongBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string lblSoDienThoai {
            get {
                return ResourceManager.GetString("lblSoDienThoai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement detail.
        /// </summary>
        internal static string lblSoToTrinh {
            get {
                return ResourceManager.GetString("lblSoToTrinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register books.
        /// </summary>
        internal static string lblSoVanBan {
            get {
                return ResourceManager.GetString("lblSoVanBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        internal static string lblSTT {
            get {
                return ResourceManager.GetString("lblSTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use.
        /// </summary>
        internal static string lblSuDung {
            get {
                return ResourceManager.GetString("lblSuDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string lblTen {
            get {
                return ResourceManager.GetString("lblTen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title.
        /// </summary>
        internal static string lblTenChucDanh {
            get {
                return ResourceManager.GetString("lblTenChucDanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title.
        /// </summary>
        internal static string lblTenChucVu {
            get {
                return ResourceManager.GetString("lblTenChucVu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name.
        /// </summary>
        internal static string lblTenCoQuan {
            get {
                return ResourceManager.GetString("lblTenCoQuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name sent/ receive.
        /// </summary>
        internal static string lblTenCoQuanGuiNhan {
            get {
                return ResourceManager.GetString("lblTenCoQuanGuiNhan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string lblTenDangNhap {
            get {
                return ResourceManager.GetString("lblTenDangNhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name.
        /// </summary>
        internal static string lblTenHienThi {
            get {
                return ResourceManager.GetString("lblTenHienThi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name.
        /// </summary>
        internal static string lblTenLoai {
            get {
                return ResourceManager.GetString("lblTenLoai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document category name.
        /// </summary>
        internal static string lblTenLoaiVanBan {
            get {
                return ResourceManager.GetString("lblTenLoaiVanBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string lblTenNguoiDung {
            get {
                return ResourceManager.GetString("lblTenNguoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usergroup name.
        /// </summary>
        internal static string lblTenNhomNguoiDung {
            get {
                return ResourceManager.GetString("lblTenNhomNguoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register name.
        /// </summary>
        internal static string lblTenSo {
            get {
                return ResourceManager.GetString("lblTenSo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register books name.
        /// </summary>
        internal static string lblTenSoVanBan {
            get {
                return ResourceManager.GetString("lblTenSoVanBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string lblTenTruyCap {
            get {
                return ResourceManager.GetString("lblTenTruyCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name.
        /// </summary>
        internal static string lblTenVaiTro {
            get {
                return ResourceManager.GetString("lblTenVaiTro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short name.
        /// </summary>
        internal static string lblTenVietTat {
            get {
                return ResourceManager.GetString("lblTenVietTat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add continue.
        /// </summary>
        internal static string lblThemLienTiep {
            get {
                return ResourceManager.GetString("lblThemLienTiep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string lblThemMoi {
            get {
                return ResourceManager.GetString("lblThemMoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add from AD.
        /// </summary>
        internal static string lblThemMoiTuAD {
            get {
                return ResourceManager.GetString("lblThemMoiTuAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding an existing user to another Branch/Dept.
        /// </summary>
        internal static string lblThemNguoiDungSanCo {
            get {
                return ResourceManager.GetString("lblThemNguoiDungSanCo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string lblThoat {
            get {
                return ResourceManager.GetString("lblThoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month/Year.
        /// </summary>
        internal static string lblThoiGianLuong {
            get {
                return ResourceManager.GetString("lblThoiGianLuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        internal static string lblThongBao {
            get {
                return ResourceManager.GetString("lblThongBao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details information of user.
        /// </summary>
        internal static string lblThongTinChiTietNguoiDung {
            get {
                return ResourceManager.GetString("lblThongTinChiTietNguoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income Details of.
        /// </summary>
        internal static string lblThongTinChiTietThuNhap {
            get {
                return ResourceManager.GetString("lblThongTinChiTietThuNhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income Information.
        /// </summary>
        internal static string lblThongTinLuong {
            get {
                return ResourceManager.GetString("lblThongTinLuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Info.
        /// </summary>
        internal static string lblThongTinNguoiDung {
            get {
                return ResourceManager.GetString("lblThongTinNguoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Information.
        /// </summary>
        internal static string lblThongTinTaiKhoan {
            get {
                return ResourceManager.GetString("lblThongTinTaiKhoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secretary.
        /// </summary>
        internal static string lblThuKy {
            get {
                return ResourceManager.GetString("lblThuKy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Scan.
        /// </summary>
        internal static string lblThuMucScan {
            get {
                return ResourceManager.GetString("lblThuMucScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        internal static string lblThuTu {
            get {
                return ResourceManager.GetString("lblThuTu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display No..
        /// </summary>
        internal static string lblThuTuHienThi {
            get {
                return ResourceManager.GetString("lblThuTuHienThi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        internal static string lblTim {
            get {
                return ResourceManager.GetString("lblTim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string lblTimKiem {
            get {
                return ResourceManager.GetString("lblTimKiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in.
        /// </summary>
        internal static string lblTimKiemTrong {
            get {
                return ResourceManager.GetString("lblTimKiemTrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string lblTrangChu {
            get {
                return ResourceManager.GetString("lblTrangChu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword.
        /// </summary>
        internal static string lblTuKhoa {
            get {
                return ResourceManager.GetString("lblTuKhoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string lblVaiTro {
            get {
                return ResourceManager.GetString("lblVaiTro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        internal static string lblVanBan {
            get {
                return ResourceManager.GetString("lblVanBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt Document.
        /// </summary>
        internal static string lblVanBanDen {
            get {
                return ResourceManager.GetString("lblVanBanDen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Document.
        /// </summary>
        internal static string lblVanBanDi {
            get {
                return ResourceManager.GetString("lblVanBanDi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Keeper.
        /// </summary>
        internal static string lblVanThu {
            get {
                return ResourceManager.GetString("lblVanThu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short.
        /// </summary>
        internal static string lblVietTat {
            get {
                return ResourceManager.GetString("lblVietTat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job title.
        /// </summary>
        internal static string lblViTriCongTac {
            get {
                return ResourceManager.GetString("lblViTriCongTac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zzzz.
        /// </summary>
        internal static string lblVTCTToNhat {
            get {
                return ResourceManager.GetString("lblVTCTToNhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete list of selected.
        /// </summary>
        internal static string lblXoaDanhSachDaChon {
            get {
                return ResourceManager.GetString("lblXoaDanhSachDaChon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete list of selected.
        /// </summary>
        internal static string lblXoaDanhSachNguoiDung {
            get {
                return ResourceManager.GetString("lblXoaDanhSachNguoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete file attachment.
        /// </summary>
        internal static string lblXoaFileDinhKem {
            get {
                return ResourceManager.GetString("lblXoaFileDinhKem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete user.
        /// </summary>
        internal static string lblXoaNguoiDung {
            get {
                return ResourceManager.GetString("lblXoaNguoiDung", resourceCulture);
            }
        }
    }
}
