//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ThemMoiCongViec {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ThemMoiCongViec() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ThemMoiCongViec", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string bcrTrangChu {
            get {
                return ResourceManager.GetString("bcrTrangChu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agree.
        /// </summary>
        internal static string btnDongY {
            get {
                return ResourceManager.GetString("btnDongY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        internal static string btnHienTai {
            get {
                return ResourceManager.GetString("btnHienTai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string btnLuu {
            get {
                return ResourceManager.GetString("btnLuu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After.
        /// </summary>
        internal static string btnSau {
            get {
                return ResourceManager.GetString("btnSau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string btnThemMoi {
            get {
                return ResourceManager.GetString("btnThemMoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string btnThoat {
            get {
                return ResourceManager.GetString("btnThoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before.
        /// </summary>
        internal static string btnTruoc {
            get {
                return ResourceManager.GetString("btnTruoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string btnXoa {
            get {
                return ResourceManager.GetString("btnXoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export .doc.
        /// </summary>
        internal static string btnXuatWord {
            get {
                return ResourceManager.GetString("btnXuatWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        internal static string lblChiaSe {
            get {
                return ResourceManager.GetString("lblChiaSe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        internal static string lblChuTri {
            get {
                return ResourceManager.GetString("lblChuTri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparation.
        /// </summary>
        internal static string lblCongTacChuanBi {
            get {
                return ResourceManager.GetString("lblCongTacChuanBi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string lblDiaDiem {
            get {
                return ResourceManager.GetString("lblDiaDiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordination Dept/Branch.
        /// </summary>
        internal static string lblDonViPhoiHop {
            get {
                return ResourceManager.GetString("lblDonViPhoiHop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        internal static string lblDoQuanTrong {
            get {
                return ResourceManager.GetString("lblDoQuanTrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        internal static string lblDoUuTien {
            get {
                return ResourceManager.GetString("lblDoUuTien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline.
        /// </summary>
        internal static string lblHanXuLy {
            get {
                return ResourceManager.GetString("lblHanXuLy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        internal static string lblHienTai {
            get {
                return ResourceManager.GetString("lblHienTai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting Schedule and Working Weekly.
        /// </summary>
        internal static string lblLichHopCongTacTuan {
            get {
                return ResourceManager.GetString("lblLichHopCongTacTuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting Schedule and Working Weekly.
        /// </summary>
        internal static string lblLichHopVaCongTacTuan {
            get {
                return ResourceManager.GetString("lblLichHopVaCongTacTuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass.
        /// </summary>
        internal static string lblMatKhau {
            get {
                return ResourceManager.GetString("lblMatKhau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinator.
        /// </summary>
        internal static string lblNguoiPhoiHop {
            get {
                return ResourceManager.GetString("lblNguoiPhoiHop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor.
        /// </summary>
        internal static string lblNguoiXuLy {
            get {
                return ResourceManager.GetString("lblNguoiXuLy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        internal static string lblNoiDung {
            get {
                return ResourceManager.GetString("lblNoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        internal static string lblNoiDung1 {
            get {
                return ResourceManager.GetString("lblNoiDung1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Content.
        /// </summary>
        internal static string lblNoiDungCongViec {
            get {
                return ResourceManager.GetString("lblNoiDungCongViec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        internal static string lblRiengTu {
            get {
                return ResourceManager.GetString("lblRiengTu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After.
        /// </summary>
        internal static string lblSau {
            get {
                return ResourceManager.GetString("lblSau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document related.
        /// </summary>
        internal static string lblTaiLieuLienQuan {
            get {
                return ResourceManager.GetString("lblTaiLieuLienQuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task name.
        /// </summary>
        internal static string lblTenCongViec {
            get {
                return ResourceManager.GetString("lblTenCongViec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        internal static string lblThang {
            get {
                return ResourceManager.GetString("lblThang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendees.
        /// </summary>
        internal static string lblThanhPhanThamDu {
            get {
                return ResourceManager.GetString("lblThanhPhanThamDu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendees.
        /// </summary>
        internal static string lblThanhPhanThamGia {
            get {
                return ResourceManager.GetString("lblThanhPhanThamGia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add continue.
        /// </summary>
        internal static string lblThemLienTiep {
            get {
                return ResourceManager.GetString("lblThemLienTiep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string lblThoiGian {
            get {
                return ResourceManager.GetString("lblThoiGian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string lblThoiGian1 {
            get {
                return ResourceManager.GetString("lblThoiGian1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string lblTrangThai {
            get {
                return ResourceManager.GetString("lblTrangThai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before.
        /// </summary>
        internal static string lblTruoc {
            get {
                return ResourceManager.GetString("lblTruoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        internal static string lblTuan {
            get {
                return ResourceManager.GetString("lblTuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your password to continue.
        /// </summary>
        internal static string lblXacNhanMatKhauEmailDeTiepTuc {
            get {
                return ResourceManager.GetString("lblXacNhanMatKhauEmailDeTiepTuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export .doc.
        /// </summary>
        internal static string lblXuatWord {
            get {
                return ResourceManager.GetString("lblXuatWord", resourceCulture);
            }
        }
    }
}
