//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ThongTinDatPhong {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ThongTinDatPhong() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ThongTinDatPhong", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string bcrTrangChu {
            get {
                return ResourceManager.GetString("bcrTrangChu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agree.
        /// </summary>
        internal static string btnDongY {
            get {
                return ResourceManager.GetString("btnDongY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string btnLuu {
            get {
                return ResourceManager.GetString("btnLuu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string btnThemMoi {
            get {
                return ResourceManager.GetString("btnThemMoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string btnThoat {
            get {
                return ResourceManager.GetString("btnThoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string btnXoa {
            get {
                return ResourceManager.GetString("btnXoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to send email to participants in the meeting?.
        /// </summary>
        internal static string lblBanCoMuonGuiEmail {
            get {
                return ResourceManager.GetString("lblBanCoMuonGuiEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mail has been sent successfully .
        /// </summary>
        internal static string lblBanGuiEmailThanhCong {
            get {
                return ResourceManager.GetString("lblBanGuiEmailThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information required.
        /// </summary>
        internal static string lblBatBuocNhapThongTin {
            get {
                return ResourceManager.GetString("lblBatBuocNhapThongTin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields marked.
        /// </summary>
        internal static string lblCacTruongCoDau {
            get {
                return ResourceManager.GetString("lblCacTruongCoDau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update booking information successfully..
        /// </summary>
        internal static string lblCapNhatThongTinDatPhongThanhCong {
            get {
                return ResourceManager.GetString("lblCapNhatThongTinDatPhongThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail booking information.
        /// </summary>
        internal static string lblChiTietThongTinDatPhong {
            get {
                return ResourceManager.GetString("lblChiTietThongTinDatPhong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting approve.
        /// </summary>
        internal static string lblChoDuyet {
            get {
                return ResourceManager.GetString("lblChoDuyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select meeting form.
        /// </summary>
        internal static string lblChonHinhThucHop {
            get {
                return ResourceManager.GetString("lblChonHinhThucHop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select user.
        /// </summary>
        internal static string lblChonNguoiDung {
            get {
                return ResourceManager.GetString("lblChonNguoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select search scope.
        /// </summary>
        internal static string lblChonPhamViTimKiem {
            get {
                return ResourceManager.GetString("lblChonPhamViTimKiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select status.
        /// </summary>
        internal static string lblChonTrangThai {
            get {
                return ResourceManager.GetString("lblChonTrangThai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        internal static string lblChuTri {
            get {
                return ResourceManager.GetString("lblChuTri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in sending email.
        /// </summary>
        internal static string lblCoLoiTrongQuaTrinhGuiEmail {
            get {
                return ResourceManager.GetString("lblCoLoiTrongQuaTrinhGuiEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string lblCoLoiXayRa {
            get {
                return ResourceManager.GetString("lblCoLoiXayRa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred please review.
        /// </summary>
        internal static string lblCoLoiXayRaVuiLongXemLai {
            get {
                return ResourceManager.GetString("lblCoLoiXayRaVuiLongXemLai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        internal static string lblConTrong {
            get {
                return ResourceManager.GetString("lblConTrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string lblDaCoLoiXayRa {
            get {
                return ResourceManager.GetString("lblDaCoLoiXayRa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booked.
        /// </summary>
        internal static string lblDaDuocDat {
            get {
                return ResourceManager.GetString("lblDaDuocDat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string lblDaHuy {
            get {
                return ResourceManager.GetString("lblDaHuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string lblDangTai {
            get {
                return ResourceManager.GetString("lblDangTai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted successfully.
        /// </summary>
        internal static string lblDaXoaThanhCong {
            get {
                return ResourceManager.GetString("lblDaXoaThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To date.
        /// </summary>
        internal static string lblDenNgay {
            get {
                return ResourceManager.GetString("lblDenNgay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string lblDiaDiem {
            get {
                return ResourceManager.GetString("lblDiaDiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space.
        /// </summary>
        internal static string lblDienTich {
            get {
                return ResourceManager.GetString("lblDienTich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string lblDoiPhong {
            get {
                return ResourceManager.GetString("lblDoiPhong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string lblDongLai {
            get {
                return ResourceManager.GetString("lblDongLai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dept/Branch.
        /// </summary>
        internal static string lblDonVi {
            get {
                return ResourceManager.GetString("lblDonVi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dept/Branch register.
        /// </summary>
        internal static string lblDonViDangKy {
            get {
                return ResourceManager.GetString("lblDonViDangKy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        internal static string lblDuyet {
            get {
                return ResourceManager.GetString("lblDuyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        internal static string lblDuyetDatPhong {
            get {
                return ResourceManager.GetString("lblDuyetDatPhong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve for meeting room reservations successfully.
        /// </summary>
        internal static string lblDuyetDatPhongHopThanhCong {
            get {
                return ResourceManager.GetString("lblDuyetDatPhongHopThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string lblEmail {
            get {
                return ResourceManager.GetString("lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File attachment.
        /// </summary>
        internal static string lblFilrDinhKem {
            get {
                return ResourceManager.GetString("lblFilrDinhKem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string lblGui {
            get {
                return ResourceManager.GetString("lblGui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send email sucessful.
        /// </summary>
        internal static string lblGuiEmailThanhCong {
            get {
                return ResourceManager.GetString("lblGuiEmailThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send email.
        /// </summary>
        internal static string lblGuiQuaEmail {
            get {
                return ResourceManager.GetString("lblGuiQuaEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send via SMS.
        /// </summary>
        internal static string lblGuiQuaSms {
            get {
                return ResourceManager.GetString("lblGuiQuaSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send document via Email.
        /// </summary>
        internal static string lblGuiVanBanquaEmail {
            get {
                return ResourceManager.GetString("lblGuiVanBanquaEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit a booking request successfully..
        /// </summary>
        internal static string lblGuiYeuCauDatPhongThanhCong {
            get {
                return ResourceManager.GetString("lblGuiYeuCauDatPhongThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting form.
        /// </summary>
        internal static string lblHinhThucHop {
            get {
                return ResourceManager.GetString("lblHinhThucHop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Meeting with.
        /// </summary>
        internal static string lblHopTrucTuyenVoi {
            get {
                return ResourceManager.GetString("lblHopTrucTuyenVoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string lblHuyDuyet {
            get {
                return ResourceManager.GetString("lblHuyDuyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No result.
        /// </summary>
        internal static string lblKhongCoKQ {
            get {
                return ResourceManager.GetString("lblKhongCoKQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget.
        /// </summary>
        internal static string lblKinhPhi {
            get {
                return ResourceManager.GetString("lblKinhPhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        internal static string lblLanhDaoChuTri {
            get {
                return ResourceManager.GetString("lblLanhDaoChuTri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        internal static string lblLuuY {
            get {
                return ResourceManager.GetString("lblLuuY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        internal static string lblLyDo {
            get {
                return ResourceManager.GetString("lblLyDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason for refusal.
        /// </summary>
        internal static string lblLyDoTuChoi {
            get {
                return ResourceManager.GetString("lblLyDoTuChoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        internal static string lblNgayBatDau {
            get {
                return ResourceManager.GetString("lblNgayBatDau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date cannot be greater than the end date.
        /// </summary>
        internal static string lblNgayBatDauKhongDuocLonHonNgayKT {
            get {
                return ResourceManager.GetString("lblNgayBatDauKhongDuocLonHonNgayKT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        internal static string lblNgayKetThuc {
            get {
                return ResourceManager.GetString("lblNgayKetThuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date must be greater than start date.
        /// </summary>
        internal static string lblNgayKTPhaiLonHonNgayBatDau {
            get {
                return ResourceManager.GetString("lblNgayKTPhaiLonHonNgayBatDau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register .
        /// </summary>
        internal static string lblNguoiDangKy {
            get {
                return ResourceManager.GetString("lblNguoiDangKy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register .
        /// </summary>
        internal static string lblNguoiDat {
            get {
                return ResourceManager.GetString("lblNguoiDat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string lblNguoiDung {
            get {
                return ResourceManager.GetString("lblNguoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget.
        /// </summary>
        internal static string lblNguonKinhPhi {
            get {
                return ResourceManager.GetString("lblNguonKinhPhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter an email.
        /// </summary>
        internal static string lblNhapEmail {
            get {
                return ResourceManager.GetString("lblNhapEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retype.
        /// </summary>
        internal static string lblNhapLai {
            get {
                return ResourceManager.GetString("lblNhapLai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter reason for refusal.
        /// </summary>
        internal static string lblNhapLyDoTuChoi {
            get {
                return ResourceManager.GetString("lblNhapLyDoTuChoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter owner.
        /// </summary>
        internal static string lblNhapNguoiChuTri {
            get {
                return ResourceManager.GetString("lblNhapNguoiChuTri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter user.
        /// </summary>
        internal static string lblNhapNguoiDung {
            get {
                return ResourceManager.GetString("lblNhapNguoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter receiver&apos;s email.
        /// </summary>
        internal static string lblNhapNguoiDungNhanEmail {
            get {
                return ResourceManager.GetString("lblNhapNguoiDungNhanEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter budget.
        /// </summary>
        internal static string lblNhapNguonKinhPhi {
            get {
                return ResourceManager.GetString("lblNhapNguonKinhPhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a phonenumber.
        /// </summary>
        internal static string lblNhapSoDienThoai {
            get {
                return ResourceManager.GetString("lblNhapSoDienThoai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter attendees.
        /// </summary>
        internal static string lblNhapSoNguoiThamGia {
            get {
                return ResourceManager.GetString("lblNhapSoNguoiThamGia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the attendees list.
        /// </summary>
        internal static string lblNhapThanhPhanThamDu {
            get {
                return ResourceManager.GetString("lblNhapThanhPhanThamDu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a keysearch.
        /// </summary>
        internal static string lblNhapTuKhoaTimKiem {
            get {
                return ResourceManager.GetString("lblNhapTuKhoaTimKiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a require.
        /// </summary>
        internal static string lblNhapYeuCau {
            get {
                return ResourceManager.GetString("lblNhapYeuCau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        internal static string lblNoiDung {
            get {
                return ResourceManager.GetString("lblNoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting content.
        /// </summary>
        internal static string lblNoiDungCuocHop {
            get {
                return ResourceManager.GetString("lblNoiDungCuocHop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting content.
        /// </summary>
        internal static string lblNoiDungHop {
            get {
                return ResourceManager.GetString("lblNoiDungHop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string lblNuoc {
            get {
                return ResourceManager.GetString("lblNuoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope.
        /// </summary>
        internal static string lblPhamVi {
            get {
                return ResourceManager.GetString("lblPhamVi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management booking information .
        /// </summary>
        internal static string lblQuanLyThongTinDatPhong {
            get {
                return ResourceManager.GetString("lblQuanLyThongTinDatPhong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string lblSoDienThoai {
            get {
                return ResourceManager.GetString("lblSoDienThoai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string lblSoNguoi {
            get {
                return ResourceManager.GetString("lblSoNguoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string lblSoNguoiThamGia {
            get {
                return ResourceManager.GetString("lblSoNguoiThamGia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity.
        /// </summary>
        internal static string lblSucChua {
            get {
                return ResourceManager.GetString("lblSucChua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dept/Branch name.
        /// </summary>
        internal static string lblTenDonVi {
            get {
                return ResourceManager.GetString("lblTenDonVi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register name.
        /// </summary>
        internal static string lblTenNguoiDangKy {
            get {
                return ResourceManager.GetString("lblTenNguoiDangKy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room name.
        /// </summary>
        internal static string lblTenPhong {
            get {
                return ResourceManager.GetString("lblTenPhong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room name.
        /// </summary>
        internal static string lblTenPhongHop {
            get {
                return ResourceManager.GetString("lblTenPhongHop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Components.
        /// </summary>
        internal static string lblThanhPhan {
            get {
                return ResourceManager.GetString("lblThanhPhan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add continue.
        /// </summary>
        internal static string lblThemLienTiep {
            get {
                return ResourceManager.GetString("lblThemLienTiep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new booking meeting room information successfully.
        /// </summary>
        internal static string lblThemMoiThongTinDatPhongThanhCong {
            get {
                return ResourceManager.GetString("lblThemMoiThongTinDatPhongThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string lblThoat {
            get {
                return ResourceManager.GetString("lblThoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string lblThoiGian {
            get {
                return ResourceManager.GetString("lblThoiGian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time is not greater than end time.
        /// </summary>
        internal static string lblThoiGianBatDauKhongDuocLonHonTGKetThuc {
            get {
                return ResourceManager.GetString("lblThoiGianBatDauKhongDuocLonHonTGKetThuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        internal static string lblThongBao {
            get {
                return ResourceManager.GetString("lblThongBao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking information.
        /// </summary>
        internal static string lblThongTinDatPhong {
            get {
                return ResourceManager.GetString("lblThongTinDatPhong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation information can not be canceled due to current usage.
        /// </summary>
        internal static string lblThongTinDatPhongKhongHuyDuocDoSuDung {
            get {
                return ResourceManager.GetString("lblThongTinDatPhongKhongHuyDuocDoSuDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation information can not be deleted due to being processed.
        /// </summary>
        internal static string lblThongTinDatPhongKhongTheXoaDuoc {
            get {
                return ResourceManager.GetString("lblThongTinDatPhongKhongTheXoaDuoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string lblThuong {
            get {
                return ResourceManager.GetString("lblThuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string lblTimKiem {
            get {
                return ResourceManager.GetString("lblTimKiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string lblTrangChu {
            get {
                return ResourceManager.GetString("lblTrangChu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string lblTrangThai {
            get {
                return ResourceManager.GetString("lblTrangThai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        internal static string lblTrangThietBi {
            get {
                return ResourceManager.GetString("lblTrangThietBi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        internal static string lblTrucTuyen {
            get {
                return ResourceManager.GetString("lblTrucTuyen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refusal to approve the booking successfully.
        /// </summary>
        internal static string lblTuChoiPheDuyetDatPhongThanhCong {
            get {
                return ResourceManager.GetString("lblTuChoiPheDuyetDatPhongThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        internal static string lblTuChoiPheDuyetYeuCauDatPhong {
            get {
                return ResourceManager.GetString("lblTuChoiPheDuyetYeuCauDatPhong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword.
        /// </summary>
        internal static string lblTuKhoa {
            get {
                return ResourceManager.GetString("lblTuKhoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string lblTuNgay {
            get {
                return ResourceManager.GetString("lblTuNgay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete list of selected.
        /// </summary>
        internal static string lblXoaDanhSachDaChon {
            get {
                return ResourceManager.GetString("lblXoaDanhSachDaChon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete file attachment.
        /// </summary>
        internal static string lblXoaFileDinhKem {
            get {
                return ResourceManager.GetString("lblXoaFileDinhKem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires.
        /// </summary>
        internal static string lblYeuCau {
            get {
                return ResourceManager.GetString("lblYeuCau", resourceCulture);
            }
        }
    }
}
