//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TinTuc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TinTuc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.TinTuc", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ban Hành.
        /// </summary>
        internal static string btnBanHanh {
            get {
                return ResourceManager.GetString("btnBanHanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đóng .
        /// </summary>
        internal static string btnDong {
            get {
                return ResourceManager.GetString("btnDong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        internal static string btnLuu {
            get {
                return ResourceManager.GetString("btnLuu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu và trình.
        /// </summary>
        internal static string btnLuuVaTrinh {
            get {
                return ResourceManager.GetString("btnLuuVaTrinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập lại.
        /// </summary>
        internal static string btnNhapLai {
            get {
                return ResourceManager.GetString("btnNhapLai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thoát.
        /// </summary>
        internal static string btnThoat {
            get {
                return ResourceManager.GetString("btnThoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trả lại.
        /// </summary>
        internal static string btnTraLai {
            get {
                return ResourceManager.GetString("btnTraLai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trình người duyệt 2.
        /// </summary>
        internal static string btnTrinhNguoiDuyet2 {
            get {
                return ResourceManager.GetString("btnTrinhNguoiDuyet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ban hành.
        /// </summary>
        internal static string lblBanHanh {
            get {
                return ResourceManager.GetString("lblBanHanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bắt buộc nhập thông tin.
        /// </summary>
        internal static string lblBatBuocNhapThongTin {
            get {
                return ResourceManager.GetString("lblBatBuocNhapThongTin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các trường có dấu.
        /// </summary>
        internal static string lblCacTruongCoDau {
            get {
                return ResourceManager.GetString("lblCacTruongCoDau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật.
        /// </summary>
        internal static string lblCapNhat {
            get {
                return ResourceManager.GetString("lblCapNhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật tin tức.
        /// </summary>
        internal static string lblCapNhatTinTuc {
            get {
                return ResourceManager.GetString("lblCapNhatTinTuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết bản tin.
        /// </summary>
        internal static string lblChiTietBanTin {
            get {
                return ResourceManager.GetString("lblChiTietBanTin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết tin tức.
        /// </summary>
        internal static string lblChiTietTinTuc {
            get {
                return ResourceManager.GetString("lblChiTietTinTuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chờ duyệt cấp 1.
        /// </summary>
        internal static string lblChoDuyetCap1 {
            get {
                return ResourceManager.GetString("lblChoDuyetCap1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chờ duyệt cấp 2.
        /// </summary>
        internal static string lblChoDuyetCap2 {
            get {
                return ResourceManager.GetString("lblChoDuyetCap2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khu vực nhận.
        /// </summary>
        internal static string lblChonKhuVuc {
            get {
                return ResourceManager.GetString("lblChonKhuVuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyên mục.
        /// </summary>
        internal static string lblChuyenMuc {
            get {
                return ResourceManager.GetString("lblChuyenMuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã tồn tại.
        /// </summary>
        internal static string lblDaTonTai {
            get {
                return ResourceManager.GetString("lblDaTonTai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xóa thành công.
        /// </summary>
        internal static string lblDaXoaThanhCong {
            get {
                return ResourceManager.GetString("lblDaXoaThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xuất bản.
        /// </summary>
        internal static string lblDaXuatBan {
            get {
                return ResourceManager.GetString("lblDaXuatBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duyệt.
        /// </summary>
        internal static string lblDuyet {
            get {
                return ResourceManager.GetString("lblDuyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiển thị thành công tin tức.
        /// </summary>
        internal static string lblHienThiThanhCongTinTuc {
            get {
                return ResourceManager.GetString("lblHienThiThanhCongTinTuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình thức đăng tin.
        /// </summary>
        internal static string lblHinhThucDangTin {
            get {
                return ResourceManager.GetString("lblHinhThucDangTin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khu vực nhận.
        /// </summary>
        internal static string lblKhuVucNhan {
            get {
                return ResourceManager.GetString("lblKhuVucNhan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lí do trả lại.
        /// </summary>
        internal static string lblLiDo {
            get {
                return ResourceManager.GetString("lblLiDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày xuất bản.
        /// </summary>
        internal static string lblNgayXuatBan {
            get {
                return ResourceManager.GetString("lblNgayXuatBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người duyệt cấp 1.
        /// </summary>
        internal static string lblNguoiDuyetCap1 {
            get {
                return ResourceManager.GetString("lblNguoiDuyetCap1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người duyệt cấp 2.
        /// </summary>
        internal static string lblNguoiDuyetCap2 {
            get {
                return ResourceManager.GetString("lblNguoiDuyetCap2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người xem.
        /// </summary>
        internal static string lblNguoiXem {
            get {
                return ResourceManager.GetString("lblNguoiXem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập khu vực nhận.
        /// </summary>
        internal static string lblNhapKhuVucNhan {
            get {
                return ResourceManager.GetString("lblNhapKhuVucNhan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập người nhận.
        /// </summary>
        internal static string lblNhapNguoiNhan {
            get {
                return ResourceManager.GetString("lblNhapNguoiNhan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập người xem.
        /// </summary>
        internal static string lblNhapNguoiXem {
            get {
                return ResourceManager.GetString("lblNhapNguoiXem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập nội dung.
        /// </summary>
        internal static string lblNhapNoiDung {
            get {
                return ResourceManager.GetString("lblNhapNoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập tên tin tức.
        /// </summary>
        internal static string lblNhapTenTinTuc {
            get {
                return ResourceManager.GetString("lblNhapTenTinTuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập từ khóa tìm kiếm.
        /// </summary>
        internal static string lblNhapTuKhoaTimKiem {
            get {
                return ResourceManager.GetString("lblNhapTuKhoaTimKiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm người nhận.
        /// </summary>
        internal static string lblNhomNguoiNhan {
            get {
                return ResourceManager.GetString("lblNhomNguoiNhan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung.
        /// </summary>
        internal static string lblNoiDung {
            get {
                return ResourceManager.GetString("lblNoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý tin tức.
        /// </summary>
        internal static string lblQuanlyTinTuc {
            get {
                return ResourceManager.GetString("lblQuanlyTinTuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành Công.
        /// </summary>
        internal static string lblThanhCong {
            get {
                return ResourceManager.GetString("lblThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới.
        /// </summary>
        internal static string lblThemMoi {
            get {
                return ResourceManager.GetString("lblThemMoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới tin tức.
        /// </summary>
        internal static string lblThemMoiTinTuc {
            get {
                return ResourceManager.GetString("lblThemMoiTinTuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        internal static string lblThongBao {
            get {
                return ResourceManager.GetString("lblThongBao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thứ tự.
        /// </summary>
        internal static string lblThuTu {
            get {
                return ResourceManager.GetString("lblThuTu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề.
        /// </summary>
        internal static string lblTieuDe {
            get {
                return ResourceManager.GetString("lblTieuDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        internal static string lblTimKiem {
            get {
                return ResourceManager.GetString("lblTimKiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin Tức.
        /// </summary>
        internal static string lblTinTuc {
            get {
                return ResourceManager.GetString("lblTinTuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin Tức hiện đang hiển thị.
        /// </summary>
        internal static string lblTinTucHienDangHienThi {
            get {
                return ResourceManager.GetString("lblTinTucHienDangHienThi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin Tức.
        /// </summary>
        internal static string lblTinTucInHoa {
            get {
                return ResourceManager.GetString("lblTinTucInHoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin tức không xóa được do đang sử dụng.
        /// </summary>
        internal static string lblTinTucKhongXoaDuocDoDangSuDung {
            get {
                return ResourceManager.GetString("lblTinTucKhongXoaDuocDoDangSuDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trả lại tin tức.
        /// </summary>
        internal static string lblTraLaiTinTuc {
            get {
                return ResourceManager.GetString("lblTraLaiTinTuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        internal static string lblTrangChu {
            get {
                return ResourceManager.GetString("lblTrangChu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        internal static string lblTrangThai {
            get {
                return ResourceManager.GetString("lblTrangThai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận thu hồi.
        /// </summary>
        internal static string lblXacNhanThuHoi {
            get {
                return ResourceManager.GetString("lblXacNhanThuHoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa danh sách đã chọn.
        /// </summary>
        internal static string lblXoaDanhSachDaChon {
            get {
                return ResourceManager.GetString("lblXoaDanhSachDaChon", resourceCulture);
            }
        }
    }
}
