//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VanPhongPham {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VanPhongPham() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.VanPhongPham", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type required information.
        /// </summary>
        internal static string lblBatBuocNhapThongTin {
            get {
                return ResourceManager.GetString("lblBatBuocNhapThongTin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields marked.
        /// </summary>
        internal static string lblCacTruongCoDau {
            get {
                return ResourceManager.GetString("lblCacTruongCoDau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật danh sách đăng ký.
        /// </summary>
        internal static string lblCapNhatDanhMucVatPham {
            get {
                return ResourceManager.GetString("lblCapNhatDanhMucVatPham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật định mức.
        /// </summary>
        internal static string lblCapNhatDinhMuc {
            get {
                return ResourceManager.GetString("lblCapNhatDinhMuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật phòng ban.
        /// </summary>
        internal static string lblCapNhatPhongBan {
            get {
                return ResourceManager.GetString("lblCapNhatPhongBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail Item.
        /// </summary>
        internal static string lblChiTietDanhMucVatPham {
            get {
                return ResourceManager.GetString("lblChiTietDanhMucVatPham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string lblDinhMuc {
            get {
                return ResourceManager.GetString("lblDinhMuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string lblDong {
            get {
                return ResourceManager.GetString("lblDong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn giá.
        /// </summary>
        internal static string lblDonGia {
            get {
                return ResourceManager.GetString("lblDonGia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dept/Branch.
        /// </summary>
        internal static string lblDonVi {
            get {
                return ResourceManager.GetString("lblDonVi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string lblDonViTinh {
            get {
                return ResourceManager.GetString("lblDonViTinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú.
        /// </summary>
        internal static string lblGhiChu {
            get {
                return ResourceManager.GetString("lblGhiChu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khu vực.
        /// </summary>
        internal static string lblKhuVuc {
            get {
                return ResourceManager.GetString("lblKhuVuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        internal static string lblLuuY {
            get {
                return ResourceManager.GetString("lblLuuY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string lblMa {
            get {
                return ResourceManager.GetString("lblMa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string lblMoTa {
            get {
                return ResourceManager.GetString("lblMoTa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Date.
        /// </summary>
        internal static string lblNgayCapNhat {
            get {
                return ResourceManager.GetString("lblNgayCapNhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tạo.
        /// </summary>
        internal static string lblNgayTao {
            get {
                return ResourceManager.GetString("lblNgayTao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người đặt.
        /// </summary>
        internal static string lblNguoiDat {
            get {
                return ResourceManager.GetString("lblNguoiDat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator.
        /// </summary>
        internal static string lblNguoiTao {
            get {
                return ResourceManager.GetString("lblNguoiTao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập đơn giá.
        /// </summary>
        internal static string lblNhapDonGia {
            get {
                return ResourceManager.GetString("lblNhapDonGia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập đơn vị tính.
        /// </summary>
        internal static string lblNhapDonViTinh {
            get {
                return ResourceManager.GetString("lblNhapDonViTinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập ghi chú.
        /// </summary>
        internal static string lblNhapGhiChu {
            get {
                return ResourceManager.GetString("lblNhapGhiChu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a Description.
        /// </summary>
        internal static string lblNhapMoTa {
            get {
                return ResourceManager.GetString("lblNhapMoTa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter an Amount.
        /// </summary>
        internal static string lblNhapSoLuong {
            get {
                return ResourceManager.GetString("lblNhapSoLuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name of Item.
        /// </summary>
        internal static string lblNhapTenVatPham {
            get {
                return ResourceManager.GetString("lblNhapTenVatPham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter search keywords.
        /// </summary>
        internal static string lblNhapTuKhoaTimKiem {
            get {
                return ResourceManager.GetString("lblNhapTuKhoaTimKiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit.
        /// </summary>
        internal static string lblPhamVi {
            get {
                return ResourceManager.GetString("lblPhamVi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng ban.
        /// </summary>
        internal static string lblPhongBan {
            get {
                return ResourceManager.GetString("lblPhongBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý định mức.
        /// </summary>
        internal static string lblQuanLyDinhMuc {
            get {
                return ResourceManager.GetString("lblQuanLyDinhMuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý đơn vị tính.
        /// </summary>
        internal static string lblQuanLyDonViTinh {
            get {
                return ResourceManager.GetString("lblQuanLyDonViTinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stationery management.
        /// </summary>
        internal static string lblQuanLyVanPhongPham {
            get {
                return ResourceManager.GetString("lblQuanLyVanPhongPham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string lblSoLuong {
            get {
                return ResourceManager.GetString("lblSoLuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use.
        /// </summary>
        internal static string lblSuDung {
            get {
                return ResourceManager.GetString("lblSuDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of item.
        /// </summary>
        internal static string lblTen {
            get {
                return ResourceManager.GetString("lblTen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng đăng ký.
        /// </summary>
        internal static string lblThangDangKy {
            get {
                return ResourceManager.GetString("lblThangDangKy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add more.
        /// </summary>
        internal static string lblThemLienTiep {
            get {
                return ResourceManager.GetString("lblThemLienTiep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new.
        /// </summary>
        internal static string lblThemMoi {
            get {
                return ResourceManager.GetString("lblThemMoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thứ tự.
        /// </summary>
        internal static string lblThuTu {
            get {
                return ResourceManager.GetString("lblThuTu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string lblTimKiem {
            get {
                return ResourceManager.GetString("lblTimKiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string lblTrangChu {
            get {
                return ResourceManager.GetString("lblTrangChu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords.
        /// </summary>
        internal static string lblTuKhoa {
            get {
                return ResourceManager.GetString("lblTuKhoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xoa định mức phòng ban.
        /// </summary>
        internal static string lblXoaDinhMucPhongBan {
            get {
                return ResourceManager.GetString("lblXoaDinhMucPhongBan", resourceCulture);
            }
        }
    }
}
