//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viags.WebApp.Pagess
{


    public partial class Home
    {

        /// <summary>
        /// ucHomeNewDesign control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Viags.WebApp.Home.ucHomeNewDesign ucHomeNewDesign;
    }
}
